const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const url=process.env.SAGAS_TEST_URL||'http://127.0.0.1:9847/';if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+\/$/.test(url))throw Error('Loopback fixture required');
const f=JSON.parse(fs.readFileSync(process.env.SAGAS_LOGIN_FIXTURE||path.resolve(__dirname,'../../.dev/fixture/synthetic-logins.json')));
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});let checks=0;const check=(v,m)=>{assert(v,m);checks++;};fs.mkdirSync('.dev/qa',{recursive:true});try{
for(const width of [1440,390,320]){const p=await b.newPage({viewport:{width,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.evaluate(t=>sessionStorage.setItem('sagas.viewer',t),f.champion);
const art='a'.repeat(64);await p.route('**/api/state?*',async r=>{const response=await r.fetch(),data=await response.json();for(const player of data.players||[])if(player.playerId==='login-champion')player.portraitId=art;await r.fulfill({response,json:data});});
await p.route('**/api/media/'+art+'?*',async r=>{check(r.request().headers().authorization==='Bearer '+f.champion,'Avatar uses authenticated media requests');await r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="96" height="144"><rect x="24" y="4" width="48" height="44" rx="20" fill="#d4b374"/><path d="M10 140V75Q48 35 86 75V140" fill="#386e77"/></svg>'});});
await p.goto(url);await p.waitForFunction(()=>state.data&&!state.busy&&loginSession?.playerId);await p.locator('#world').selectOption(f.world);await p.waitForFunction(()=>state.data?.world==='synthetic-login'&&!state.busy);await p.waitForFunction(()=>document.querySelector('#accountAvatar img')?.naturalWidth>0);
check(await p.locator('#accessButton').isHidden(),'Login replaced by account icon');check(await p.locator('#accountAvatar').evaluate(e=>e.classList.contains('has-portrait')),'Saved portrait replaces initials');await p.locator('#accountButton').focus();await p.keyboard.press('Enter');check(await p.locator('#accountMenu').isVisible(),'Keyboard opens account options');check(await p.locator('#sagaSettingsButton').evaluate(e=>e===document.activeElement),'Focus enters options');await p.keyboard.press('Escape');check(await p.locator('#accountMenu').isHidden(),'Escape dismisses options');check(await p.locator('#accountButton').evaluate(e=>e===document.activeElement),'Focus returns to account icon');
await p.locator('#accountButton').click();await p.screenshot({path:'.dev/qa/account-menu-'+width+'.png'});await p.locator('#serverName').click();check(await p.locator('#accountMenu').isHidden(),'Outside click dismisses options');await p.locator('#accountButton').click();await p.locator('#sagaSettingsButton').click();await p.waitForFunction(()=>personalLore!==null);check(await p.locator('#loreModeHost').isChecked(),'Server storyteller is the simple default');check(await p.locator('#personalLoreFields').isHidden(),'Personal key/settings are hidden by default');check(await p.locator('#access').isHidden(),'Settings are separate from login');await p.screenshot({path:'.dev/qa/saga-settings-host-'+width+'.png'});
await p.locator('#loreModePersonal').check();check(!(await p.locator('#loreAdvanced').evaluate(e=>e.open)),'Advanced options collapsed');await p.locator('#saveLoreButton').click();check((await p.locator('#loreSaveStatus').textContent()).includes('Add your OpenRouter key'),'Missing key has a helpful error');await p.locator('#personalLoreKey').fill('synthetic-key-discard-on-close');await p.locator('#sagaSettings').evaluate(e=>e.scrollTop=0);await p.screenshot({path:'.dev/qa/saga-settings-personal-'+width+'.png'});await p.keyboard.press('Escape');check((await p.locator('#personalLoreKey').inputValue())==='','Escape clears unsaved secret');check(await p.locator('#sagaSettings').isHidden(),'Escape closes settings');check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal page overflow');
await p.route('**/api/lore-settings*',r=>r.fulfill({status:503,json:{error:'Synthetic settings outage'}}));await p.locator('#accountButton').click();await p.locator('#sagaSettingsButton').click();await p.waitForFunction(()=>document.querySelector('#loreSettingsInfo').textContent.includes('Settings unavailable'));check(await p.locator('#saveLoreButton').isDisabled(),'Failed load cannot overwrite saved settings');await p.locator('#closeSagaSettings').click();await p.unroute('**/api/lore-settings*');
await p.locator('#accountButton').click();await p.locator('#forgetToken').click();await p.waitForFunction(()=>document.querySelector('#access').open);check(await p.evaluate(()=>sessionStorage.getItem('sagas.viewer')===null),'Logout clears session');check(await p.locator('#accountButton').isHidden(),'Logout hides profile icon');await p.locator('#closeAccess').click();await p.locator('#accessButton').click();check(await p.locator('#access').isVisible()&&await p.locator('#sagaSettings').isHidden(),'Signed-out button opens token-only login');check(errors.length===0,'No browser exceptions: '+errors.join(', '));await p.close();}
console.log('PASS '+checks+' account menu/avatar, keyboard/focus, default/personal settings, secret cleanup, error handling, logout and responsive checks (synthetic HTTP fixtures).');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
