/* Synthetic host only. Deliberately delayed feeds validate independent loading. */
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SAGAS_BROWSER_EXECUTABLE||(process.platform==='win32'?'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe':undefined)});try{
 const page=await browser.newPage({viewport:{width:1500,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('sagas.viewer','synthetic-development-token-only'));
 let release;const held=new Promise(r=>release=r);await page.route('**/api/state?*',async route=>{await held;await route.continue().catch(()=>{});});
 await page.goto('http://127.0.0.1:9847/#world');await page.waitForFunction(()=>state.map.cells.length>0&&!state.mapLoading);
 assert.equal(await page.evaluate(()=>!!state.data.stats),false,'Map arrives while statistics deliberately blocked');assert.equal(await page.locator('#onlineCount').textContent(),'2');await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('Statistics delayed'));
 const before=await page.evaluate(()=>view.scale);await page.locator('#zoomOut').click();assert((await page.evaluate(()=>view.scale))<before,'Map controls work during delayed statistics');release();await page.waitForFunction(()=>state.data?.stats&&!state.busy);await page.unroute('**/api/state?*');
 await page.waitForFunction(()=>document.querySelector('#recapTotals').textContent.includes('Creatures felled'));assert((await page.locator('#recapPeriod').textContent()).includes('first visit'));
 await page.reload();await page.waitForFunction(()=>document.querySelector('#recapPeriod').textContent.includes('Since your last visit'));
 await page.locator('#world').selectOption('synthetic-leaderboard');await page.waitForFunction(()=>state.data?.world==='synthetic-leaderboard'&&state.data.stats&&!state.busy);
 await page.locator('nav a[href="#leaderboard"]').click();await page.locator('[data-renown-view="trophies"]').click();await page.waitForFunction(()=>document.querySelectorAll('.trophy-card').length>=8);
 assert((await page.locator('#trophyHall').textContent()).includes('Kall Fimbulbringer'));const trophy=page.locator('.trophy-card').filter({has:page.locator('h2',{hasText:'Eikthyr'})});assert((await trophy.textContent()).includes('2 defeats'));assert((await trophy.textContent()).includes('Bjorn Shieldbearer'));assert(await page.locator('#leaderboardResults').isHidden());await page.screenshot({path:'.dev/trophies0333.png',fullPage:true});
 await page.locator('[data-renown-view="compare"]').click();await page.waitForFunction(()=>document.querySelector('#comparisonResults table'));await page.locator('#compareLeft').selectOption('trial-0');await page.locator('#compareRight').selectOption('trial-1');assert((await page.locator('#comparisonResults').textContent()).includes('Boss participation'));assert(!(await page.locator('#compareLeft').textContent()).includes('Private synthetic Viking'));
 await page.locator('#leaderboardRange').selectOption('30m');await page.locator('#leaderboardFilters button').click();await page.waitForFunction(()=>adventureData&&adventureData.from&&new Date(adventureData.to)-new Date(adventureData.from)===1800000);assert((await page.locator('#leaderboardStatus').textContent()).includes('30 minutes'));await page.screenshot({path:'.dev/compare0333.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.dev/compare0333-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile page does not overflow');
 await page.route('**/api/version?*',r=>r.fulfill({json:{serverVersion:'0.3.27',websiteVersion:'0.3.27',mismatch:true}}));await page.evaluate(()=>{versionDue=0;return refreshVersions();});assert(await page.locator('#versionWarning').isVisible());assert((await page.locator('#versionInfo').textContent()).includes('0.3.27'));
 // Chapter location presentation: synthetic API reply, real navigation/centering UI.
 await page.route('**/api/saga-map?*',r=>r.fulfill({json:{world:'synthetic-leaderboard',moments:[{id:'synthetic-only',name:'Eikthyr',kind:'kill',playerName:'Astrid',boss:true,x:100,z:200,utc:new Date().toISOString()}]}}));await page.evaluate(()=>{const button=document.createElement('button');button.dataset.chapterMap='synthetic-only';return openChapterMap(button);});await page.locator('[data-chapter-moment="0"]').click();await page.waitForFunction(()=>document.body.dataset.page==='world'&&!document.querySelector('#mapInspect').hidden);assert.equal(await page.evaluate(()=>view.x),100);assert((await page.locator('#mapInspect').textContent()).includes('Recorded event location'));// A slow statistics response must not resurrect a revoked profile from an older snapshot.
 await page.unroute('**/api/state?*').catch(()=>{});await page.evaluate(()=>{worldDue=Infinity;});let allowOld,gotOld;const oldHeld=new Promise(r=>allowOld=r),captured=new Promise(r=>gotOld=r);
 await page.route('**/api/state?*',async route=>{const response=await route.fetch();const json=await response.json();gotOld();await oldHeld;await route.fulfill({response,json}).catch(()=>{});});
 await page.evaluate(()=>{state.busy=false;refresh();});await captured;
 await page.route('**/api/world-state?*',async route=>{const response=await route.fetch();const json=await response.json();const p=json.players.find(p=>p.playerId==='trial-0');p.shareProfile=false;p.shareMap=false;p.gear=[];p.hotbar=[];p.portraitId='';await route.fulfill({response,json});});
 await page.evaluate(()=>{worldDue=0;return refreshWorld();});assert.equal(await page.evaluate(()=>state.data.players.find(p=>p.playerId==='trial-0').shareProfile),false);allowOld();await page.waitForFunction(()=>!state.busy);assert.equal(await page.evaluate(()=>state.data.players.find(p=>p.playerId==='trial-0').shareProfile),false,'Late history cannot restore revoked profile');assert.equal(await page.evaluate(()=>state.data.stats),null,'Stale aggregate waits for fresh permission-aware query');
 assert.deepEqual(errors,[]);console.log('PASS independent map loading, slow-feed status, version mismatch, per-world recap bookmarks, trophies, comparisons/filters/privacy, mobile layout, chapter map navigation.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
