/* Synthetic canvas regression. Runs production heatmap functions, no game or server needed. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const source=fs.readFileSync(path.resolve(__dirname,'../../src/Sagas.Web/app.js'),'utf8');
const functions=source.slice(source.indexOf('function heatBuckets('),source.indexOf('function positionInspect('));
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SAGAS_BROWSER_EXECUTABLE||(process.platform==='win32'?'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe':undefined)});try{const page=await browser.newPage();const results=await page.evaluate(code=>{
 const view={x:0,z:0,scale:1,width:500,height:500};function screen(x,z){return [(x-view.x)*view.scale+view.width/2,(view.z-z)*view.scale+view.height/2];}
 return eval(code+`\n(()=>{
 const events=[{kind:'kill',x:1,z:1,count:3},{kind:'kill',x:31,z:31},{kind:'collect',x:2,z:2,amount:50},{kind:'kill',x:-1,z:-1},{kind:'kill',x:32,z:0,count:9}];
 const bins=heatBuckets(events),snapshot=JSON.stringify(bins);view.x=271;view.z=-105;view.scale=2;const stable=snapshot===JSON.stringify(heatBuckets(events));view.x=0;view.z=0;view.scale=1;
 const reversed=heatBuckets([...events].reverse());const keysStable=bins.map(h=>h.key).join('|')===reversed.map(h=>h.key).join('|');
 const kills=heatBuckets(events.filter(e=>e.kind==='kill')),loot=heatBuckets(events.filter(e=>e.kind==='collect'));
 function paint(rows,x=0,z=0,intensity=1){view.x=x;view.z=z;const canvas=document.createElement('canvas');canvas.width=canvas.height=500;const ctx=canvas.getContext('2d');ctx.fillStyle='#0a1319';ctx.fillRect(0,0,500,500);drawHeat(ctx,rows,heatPeaks(rows),intensity);const p=screen(16,16),sample=[...ctx.getImageData(p[0],p[1],1,1).data];return {sample,all:Array.from(ctx.getImageData(0,0,500,500).data),mode:ctx.globalCompositeOperation};}
 const local=[{kind:'kill',x:1,z:1},{kind:'collect',x:1,z:1,amount:500}],one=heatBuckets(local.filter(e=>e.kind==='kill')),two=heatBuckets(local.filter(e=>e.kind==='collect')),both=heatBuckets(local),a=paint(both),b=paint(both,11,-8),warm=paint(one).sample,cool=paint(two).sample,mixed=a.sample;
 return {stable,keysStable,keys:bins.map(h=>h.key),bin:bins.find(h=>h.key==='0,0'),peaks:heatPeaks(bins),killPeak:heatPeaks(kills).kills,lootPeak:heatPeaks(loot).loot,panPixels:a.sample.every((v,i)=>Math.abs(v-b.sample[i])<=1),warm,cool,mixed,reversePixels:JSON.stringify(paint(heatBuckets(local.slice().reverse())).all)===JSON.stringify(a.all),restored:a.mode,intensity:paint(one,0,0,.25).sample[0]<warm[0],invalid:heatBuckets([{kind:'kill',x:NaN,z:1},{kind:'collect',x:0,z:0,amount:Infinity}]).length};
 })()`);
 },functions);
 assert(results.stable,'Pan and zoom leave world grouping unchanged');assert(results.keysStable,'Input order leaves drawing order unchanged');assert.deepEqual(results.keys,['-1,-1','0,0','1,0'],'World bins use floor across negative coordinates');assert.equal(results.bin.kills,4);assert.equal(results.bin.loot,50);assert.equal(results.bin.weight,54);assert.equal(results.peaks.kills,results.killPeak,'Loot cannot rescale kill density');assert.equal(results.peaks.loot,results.lootPeak);assert(results.panPixels,'Panning preserves heat pixel colors');assert(results.warm[0]>results.warm[2],'Kills use warm hue');assert(results.cool[2]>results.cool[0],'Loot uses cool hue');assert(results.mixed[0]>=results.warm[0]&&results.mixed[2]>=results.cool[2],'Overlap blends contributions without priority');assert(results.reversePixels,'Event order cannot change composited pixels');assert.equal(results.restored,'source-over','Blend state does not leak onto markers');assert(results.intensity,'Intensity changes brightness');assert.equal(results.invalid,0);console.log('PASS 16 world-space heatmap, independent palette, density, order, blend and canvas regressions.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
