// Synthetic DevHost only. Real production journey code and HTTP privacy boundary.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
// Curve endpoints stay recorded; the S bend remains stable in world space.
const curveSource=fs.readFileSync('../../src/Sagas.Web/journey.js','utf8');
const trailPoint=new Function(curveSource.match(/function trailPoint\(a,b,t\)\{[^\n]+/)[0]+'; return trailPoint;')();
const a={x:0,z:0},b={x:200,z:0};assert.deepEqual(trailPoint(a,b,0),a);assert(Math.hypot(trailPoint(a,b,1).x-b.x,trailPoint(a,b,1).z-b.z)<1e-9);assert(trailPoint(a,b,.25).z>0);assert(trailPoint(a,b,.75).z<0);assert.deepEqual(trailPoint(a,a,.5),a);
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1150}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('sagas.viewer','synthetic-development-token-only'));
 let indexCalls=0;page.on('request',r=>{if(r.url().includes('/api/saga-journeys?'))indexCalls++;});
 await page.goto('http://127.0.0.1:9847');await page.waitForFunction(()=>state.data?.players?.length&&!state.busy);assert.equal(indexCalls,0,'Journey feed is lazy until layer or dedicated page is used');
 await page.locator('#world').selectOption('synthetic-journey');await page.waitForFunction(()=>state.data.world==='synthetic-journey'&&!state.busy&&!state.mapLoading);
 await page.locator('#journeyToggle').click();await page.waitForFunction(()=>document.querySelector('#journeyList').textContent.includes('Where the thunder answered'));assert(indexCalls>0);
 // The layer may stay enabled, but only the open tray looks selected.
 await page.locator('[data-atlas-tray="terrain"]').click();assert.equal(await page.locator('#journeyToggle').getAttribute('aria-expanded'),'false');assert(!(await page.locator('#journeyToggle').getAttribute('class')||'').includes('is-active'));await page.locator('#journeyToggle').click();
 await page.locator('#journeyList button').filter({hasText:'Where the thunder answered'}).click();await page.waitForFunction(()=>SagaJourney.debug().points===5);assert(await page.locator('#journeyStory').isVisible());assert.equal(await page.locator('#journeyTimeline button').count(),5);
 const layoutCheck=await page.evaluate(()=>{const dock=$('journeyDock').getBoundingClientRect(),nav=document.querySelector('.atlas-navigation').getBoundingClientRect(),d=SagaJourney.debug(),xs=d.moments.map(p=>p.x),zs=d.moments.map(p=>p.z);return {clear:dock.bottom<nav.top,center:Math.abs(view.x-(Math.min(...xs)+Math.max(...xs))/2)<1,visible:d.moments.every(p=>{const [x,y]=screen(p.x,p.z);return x>20&&x<canvas.clientWidth-20&&y>70&&y<canvas.clientHeight-150;})};});assert(layoutCheck.clear,'Replay clears map navigation');assert(layoutCheck.center&&layoutCheck.visible,'Opening saga fits its moments');
 await page.locator('[data-journey-moment="0"]').click();assert((await page.locator('.journey-landscape').getAttribute('src')).includes('meadows'));assert.equal(await page.locator('.journey-boss').count(),0);
 await page.locator('[data-journey-moment="2"]').click();await page.waitForFunction(()=>document.querySelector('.journey-boss')?.naturalWidth>0);assert((await page.locator('#journeyEvidence').textContent()).includes('Eikthyr'));
 assert((await page.locator('.journey-landscape').getAttribute('src')).includes('black-forest'));await page.locator('[data-journey-moment="3"]').click();assert.equal(await page.locator('.journey-boss').count(),0,'Boss art clears on ordinary moment');await page.locator('[data-journey-moment="2"]').click();
 await page.locator('.journey-read').click();await page.waitForFunction(()=>document.body.dataset.page==='journey');assert((await page.locator('#journeyChapter').textContent()).includes('Synthetic narrative'));assert.equal(await page.locator('#map').count(),1,'Only one terrain renderer, relocated to chapter view');
 await page.evaluate(()=>{$('killLayer').checked=false;drawMap();$('journeyFollow').checked=false;});
 const geometry=await page.evaluate(()=>({map:canvas.getBoundingClientRect().height,panel:$('journeyStory').getBoundingClientRect().height}));assert(Math.abs(geometry.map-geometry.panel)<3,'Story cannot stretch the map');
 await page.locator('#journeyPlay').click();await page.waitForFunction(()=>SagaJourney.debug().position>2.15);assert.equal(await page.locator('#journeyPlay').getAttribute('aria-label'),'Pause journey');
 // Terrain redraw count during replay should remain stationary between feed arrivals.
 await page.evaluate(()=>{window.journeyDraws=0;window.savedDraw=terrainAtlas.draw.bind(terrainAtlas);terrainAtlas.draw=(...args)=>{journeyDraws++;return savedDraw(...args);};});await page.waitForTimeout(550);assert((await page.evaluate(()=>journeyDraws))<6,'Replay does not redraw terrain at animation cadence');await page.evaluate(()=>{terrainAtlas.draw=savedDraw;});
 await page.locator('#journeyPlay').click();const paused=await page.evaluate(()=>SagaJourney.debug().position);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>SagaJourney.debug().position),paused);
 await page.evaluate(()=>{$('journeyScrub').value=4;$('journeyScrub').dispatchEvent(new Event('input'));});assert.equal(await page.locator('#journeyCount').textContent(),'5 / 5');await page.locator('#journeyPlay').click();await page.waitForFunction(()=>SagaJourney.debug().position<1);await page.locator('#journeyPlay').click();
 await page.locator('[data-journey-moment="2"]').click();await page.locator('#journeyFit').click();await page.locator('#journeyPage').screenshot({path:'../../TestingOutputs/saga-journey-0335-desktop.png'});
 await page.locator('.journey-back').click();await page.waitForFunction(()=>document.body.dataset.page==='world');assert(await page.locator('#worldPage #atlas').count());
 await page.locator('#journeyToggle').click();await page.locator('#journeyLayer').uncheck();assert.equal(await page.evaluate(()=>SagaJourney.debug().playing),false);assert(await page.locator('#journeyStory').isHidden());
 // Changed map scope clears old points and prevents a delayed response from restoring them.
 await page.locator('#journeyLayer').check();await page.locator('#journeyList button').filter({hasText:'Where the thunder answered'}).click();await page.waitForFunction(()=>SagaJourney.debug().points===5);
 let release,arrived;const gate=new Promise(r=>release=r),got=new Promise(r=>arrived=r);await page.route('**/api/saga-journey?*',async route=>{const response=await route.fetch();arrived();await gate;await route.fulfill({response}).catch(()=>{});});
 await page.locator('#journeyList button').filter({hasText:'Where the thunder answered'}).click();await got;await page.evaluate(()=>{state.mapPlayers=['no-consenting-player'];SagaJourney.reset();});release();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>SagaJourney.debug().points),0);assert.equal(await page.locator('#journeyStory').textContent(),'','Revoked content removed from DOM');await page.unroute('**/api/saga-journey?*');
 await page.evaluate(()=>{state.mapPlayers=[];location.hash='journey/synthetic-thunder';});await page.waitForFunction(()=>SagaJourney.debug().points===5);
 for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.waitForTimeout(120);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile does not overflow '+width);assert(await page.evaluate(()=>$('journeyDock').getBoundingClientRect().bottom<document.querySelector('.atlas-navigation').getBoundingClientRect().top),'Mobile playback clears navigation');if(width===390)await page.locator('#journeyPage').screenshot({path:'../../TestingOutputs/saga-journey-0335-mobile.png'});}
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#journeyPlay').click();await page.waitForTimeout(150);assert(await page.evaluate(()=>SagaJourney.debug().playing),'Explicit replay works with reduced motion; decorative arrow is omitted');await page.locator('#journeyPlay').click();
 await page.evaluate(()=>{location.hash='journey/does-not-exist';});await page.waitForFunction(()=>document.querySelector('#journeyTitle').textContent==='Chapter unavailable');assert(await page.locator('#journeyStory').isHidden());
 await page.setViewportSize({width:1600,height:1150});await page.route('**/api/saga-journey?*',async route=>{const r=await route.fetch(),d=await r.json();d.moments=Array.from({length:6},(_,i)=>({...d.moments[0],id:'coincident-'+i,x:0,z:0,breakBefore:i===0}));await route.fulfill({response:r,json:d});});await page.evaluate(()=>location.hash='journey/synthetic-thunder');await page.waitForFunction(()=>SagaJourney.debug().points===6);await page.waitForTimeout(150);const markers=await page.evaluate(()=>SagaJourney.debug().markers);assert.equal(markers.length,6);for(let i=0;i<6;i++)for(let j=i+1;j<6;j++)assert(Math.hypot(markers[i].x-markers[j].x,markers[i].y-markers[j].y)>55,'Coincident moments remain separately selectable');await page.unroute('**/api/saga-journey?*');
 const fresh=await browser.newPage();await fresh.addInitScript(()=>localStorage.setItem('sagas.viewer','synthetic-development-token-only'));await fresh.goto('http://127.0.0.1:9847/#journey/synthetic-thunder?world=synthetic-journey');await fresh.waitForFunction(()=>window.SagaJourney?.debug().points===5&&state.filter.world==='synthetic-journey');await fresh.close();assert.deepEqual(errors,[]);console.log('PASS lazy feed, real chapter API, local art, map relocation, play/pause/replay/scrub, isolated terrain animation, privacy race, unavailable chapter, desktop/mobile and reduced motion.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
