const {revealAtlas}=require('./atlas-controls.cjs');
// Isolated synthetic DevHost only. No game/world files or external requests.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SAGAS_BROWSER_EXECUTABLE||(process.platform==='win32'?'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe':undefined)});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:9847/');await page.locator('#token').fill('synthetic-development-token-only');await page.locator('#accessForm button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('Connected'));
 await page.waitForFunction(()=>mapPins.length===3);let checks=0;const check=(v,m)=>{assert(v,m);checks++;};
 check(await page.locator('#gamePinsLayer').isChecked(),'Game icons default enabled');check(!await page.locator('#personalPinsLayer').isChecked(),'Personal icons default hidden in browser');check(await page.evaluate(()=>visibleMapPins().length===2),'Two game icons visible');
 await revealAtlas(page,'icons');await page.locator('#personalPinsLayer').check();check(await page.evaluate(()=>visibleMapPins().length===3),'Personal toggle reveals consented pin');await revealAtlas(page,'icons');await page.locator('#gamePinsLayer').uncheck();check(await page.evaluate(()=>visibleMapPins().length===1),'Game toggle independent');await revealAtlas(page,'icons');await page.locator('#gamePinsLayer').check();
 check(await page.evaluate(()=>clockSnapshot.day===42),'Actual separate clock API loaded');await revealAtlas(page,'icons');await page.locator('#clockStyle').selectOption('horizon');check(await page.locator('.clock-horizon').count()===1,'Horizon graphic rendered');await revealAtlas(page,'icons');await page.locator('#clockStyle').selectOption('none');check(!await page.locator('#worldClock').isVisible(),'None hides graphic');await revealAtlas(page,'icons');await page.locator('#clockStyle').selectOption('dial');check(await page.locator('#worldClock svg').count()===1,'Dial rendered');
 await page.evaluate(()=>{clockSnapshot={world:state.filter.world,day:42,fraction:.5,utc:new Date().toISOString()};renderWorldClock();});check((await page.locator('#worldClock').getAttribute('aria-label')).includes('Daylight'),'Daylight phase accessible');await page.locator('#atlas').screenshot({path:path.resolve('.dev/map0318-desktop.png')});
 await page.evaluate(()=>{clockSnapshot.fraction=.9;clockSnapshot.utc='2020-01-01T00:00:00Z';clockInitialAge=60;renderWorldClock();});check((await page.locator('#worldClock').getAttribute('aria-label')).includes('Night, last known'),'Stale clock explicitly labelled');
 await page.evaluate(()=>{const p=mapPins.find(p=>p.personal);p.name='<img src=x onerror=alert(1)>';showMapPin(p,100,100);});check(await page.locator('#mapInspect img').count()===0,'Pin name escaped');check((await page.locator('#mapInspect').textContent()).includes('<img'),'Pin name preserved as text');
 await page.locator('#closeInspect').click();await revealAtlas(page,'terrain');await page.locator('#explorers').selectOption('fixture-1');await page.waitForFunction(()=>state.mapPlayers.includes('fixture-1')&&mapPins.length===3);check(await page.evaluate(()=>mapPins.length===3),'Terrain selection does not change independently shared icon feed');await revealAtlas(page,'terrain');await page.locator('#explorers').selectOption('');await page.waitForFunction(()=>mapPins.length===3);
 const hidden=await page.evaluate(()=>{const context=pinContext;pinContext='old-world';const result=visibleMapPins().length;pinContext=context;return result;});check(hidden===0,'Stale context pins hidden during world/filter switch');
 await revealAtlas(page,'icons');await page.locator('#clockStyle').selectOption('horizon');await page.reload();await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('Connected'));check(await page.locator('#clockStyle').inputValue()==='horizon','Clock choice persists');check(await page.locator('#personalPinsLayer').isChecked(),'Layer choice persists');
 await page.setViewportSize({width:390,height:844});await page.locator('#map').scrollIntoViewIfNeeded();await page.screenshot({path:path.resolve('.dev/map0318-mobile.png')});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile horizontal overflow');check(errors.length===0,'No browser script errors: '+errors.join('; '));console.log('PASS '+checks+' map icon, clock, privacy-context, escaping and responsive checks.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
