/* Synthetic public/private access recovery and separate-browser login checks. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const fixture=JSON.parse(fs.readFileSync(process.env.SAGAS_LOGIN_FIXTURE,'utf8'));
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});let checks=0;const check=(v,t)=>{assert(v,t);checks++;};
try{
 const setup=async(publicViewing)=>{const context=await browser.newContext();await context.route('**/api/**',async route=>{const req=route.request(),url=new URL(req.url());if(url.pathname==='/api/access')return route.fulfill({json:{requiresToken:!publicViewing}});const auth=req.headers().authorization;if(auth==='Bearer expired-synthetic')return route.fulfill({status:401,json:{error:'synthetic revoked token'}});if(!auth&&publicViewing){const response=await route.fetch({headers:{...req.headers(),authorization:'Bearer synthetic-development-token-only'}});return route.fulfill({response});}return route.continue();});return context;};
 const first=await setup(true);await first.addInitScript(()=>{if(!localStorage.getItem('synthetic-initialized')){localStorage.setItem('synthetic-initialized','yes');localStorage.setItem('sagas.viewer','expired-synthetic');}});
 const page=await first.newPage();await page.goto('http://127.0.0.1:9847/');await page.waitForFunction(()=>typeof state!=="undefined"&&state.data&&state.map.cells.length>0&&!state.busy&&state.token==='');
 check(await page.evaluate(()=>localStorage.getItem('sagas.viewer')===null),'Revoked token removed');check(!(await page.locator('#connection').textContent()).includes('Updates unavailable'),'Public map and updates recover automatically');
 const signIn=async p=>{await p.locator('#accessButton').click();await p.locator('#token').fill(fixture.champion);await p.locator('#accessForm button[type=submit]').click();await p.waitForFunction(()=>typeof loginSession!=="undefined"&&!!loginSession?.playerId);};
 await signIn(page);check(await page.evaluate(()=>!!localStorage.getItem('sagas.viewer')),'Login remembered in browser');
 const tab=await first.newPage();await tab.goto('http://127.0.0.1:9847/');await tab.waitForFunction(()=>typeof loginSession!=="undefined"&&!!loginSession?.playerId);check(await tab.evaluate(()=>!!state.token),'Another tab uses remembered login');
 const second=await setup(true),steam=await second.newPage();await steam.goto('http://127.0.0.1:9847/');await steam.waitForFunction(()=>typeof state!=="undefined"&&state.accessReady);check(await steam.evaluate(()=>!state.token),'Separate browser requires its own initial login');await signIn(steam);
 await steam.locator('#accountButton').click();await steam.locator('#forgetToken').click();await steam.waitForFunction(()=>typeof state!=="undefined"&&state.accessReady&&!state.token);
 await page.reload();await page.waitForFunction(()=>typeof loginSession!=="undefined"&&!!loginSession?.playerId);check(await page.evaluate(()=>!!state.token),'Logging out elsewhere preserves first browser');
 const privateContext=await setup(false);await privateContext.addInitScript(()=>{if(!sessionStorage.getItem('synthetic-initialized')){sessionStorage.setItem('synthetic-initialized','yes');localStorage.setItem('sagas.viewer','expired-synthetic');}});const privatePage=await privateContext.newPage();await privatePage.goto('http://127.0.0.1:9847/');await privatePage.waitForFunction(()=>typeof state!=="undefined"&&state.accessReady&&!state.token&&document.querySelector('#access').open);check(await privatePage.evaluate(()=>state.data===null),'Revoked private access returns to clean login prompt');
 console.log('PASS '+checks+' multi-browser persistence and revoked-token recovery checks (synthetic HTTP fixtures).');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
