const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.SAGAS_BROWSER_EXECUTABLE||(process.platform==='win32'?'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe':undefined)});try{const p=await b.newPage({viewport:{width:1500,height:1100}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>sessionStorage.setItem('sagas.viewer','synthetic-development-token-only'));await p.goto('http://127.0.0.1:9847/#profile/fixture-0');await p.waitForFunction(()=>state.profileData?.stats&&!state.busy);await p.waitForLoadState('networkidle');await p.evaluate(()=>{state.busy=true;worldDue=Infinity;appliedPresence=++presenceSerial;const v=state.data.players.find(p=>p.playerId==='fixture-0');v.online=true;v.lastSeenUtc=new Date().toISOString();v.completedBossKeys=['Fader'];v.progressionTier=7;v.progressionBoss='Fader';state.data.chapters=[{playerId:v.playerId,model:'synthetic-provider',characterBioModel:'synthetic-provider',utc:new Date().toISOString(),characterBio:'Astrid carried the memory of the ash coast into every journey. Beneath a sky of embers, she stood beside her companions and returned with a story worth remembering.',text:'Synthetic test chapter only.'}];render();});
for(const host of ['#online','#homeRoster'])assert(await p.locator(host+' .player-chip').evaluateAll(cards=>cards.every(c=>c.querySelectorAll('.character-avatar').length===1)),'Exactly one avatar per roster card');
const style=async selector=>p.locator(selector).evaluate(e=>{const c=getComputedStyle(e);return [e.textContent,c.color,c.backgroundColor,c.borderRadius,c.fontSize,c.fontWeight]});const original=await style('#characterStatus .profile-presence');assert.deepEqual(await style('#online [data-profile="fixture-0"] .profile-presence'),original);assert.deepEqual(await style('#homeRoster [data-profile="fixture-0"] .profile-presence'),original);
for(let n=0;n<3;n++){await p.locator('nav a[href="#profile"]').click();await p.locator('#vikingDirectory').waitFor({state:'visible'});const card=p.locator('.directory-card[data-profile="fixture-0"]');assert.deepEqual(await style('.directory-card[data-profile="fixture-0"] .profile-presence'),original);assert.equal(await card.locator('.directory-boss.complete').count(),1,JSON.stringify(await p.evaluate(()=>({keys:state.data.players[0].completedBossKeys,index:vikingIndex[0].completedBossKeys,busy:state.busy,catalog:state.data.bossCatalog?.length,card:document.querySelector('.directory-card').textContent}))));assert.equal(await card.locator('.directory-boss').count(),8);assert.equal(await card.locator('.directory-progress-heading>b').textContent(),'1 / 8');assert((await card.locator('.directory-saga-excerpt').textContent()).startsWith('Astrid carried'));await card.click();await p.locator('#vikingDirectory').waitFor({state:'hidden'});await p.locator('#characterStatus .profile-presence').waitFor({state:'visible'});assert.deepEqual(await style('#characterStatus .profile-presence'),original,'Same unchanged status survives directory -> same profile navigation');}
await p.locator('nav a[href="#profile"]').click();await p.locator('#vikingDirectory').waitFor({state:'visible'});await p.locator('#profile').screenshot({path:'.dev/cards0322-desktop.png'});await p.setViewportSize({width:390,height:844});await p.locator('#profile').screenshot({path:'.dev/cards0322-mobile.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await p.evaluate(()=>{state.data.chapters=[{playerId:'fixture-0',model:'local-template',utc:new Date().toISOString(),text:'DO NOT SHOW TEMPLATE'},{playerId:'fixture-1',model:'synthetic-provider',utc:new Date().toISOString(),text:'<img src=x onerror=alert(1)> Literal saga text'}];renderVikingDirectory();});assert((await p.locator('.directory-card[data-profile="fixture-0"] .directory-saga-excerpt').textContent()).includes('No saga'));assert.equal(await p.locator('.directory-saga img').count(),0);assert((await p.locator('.directory-card[data-profile="fixture-1"] .directory-saga-excerpt').textContent()).includes('<img'));
for(const mode of ['delayed','offline']){await p.evaluate(mode=>{const v=state.data.players.find(p=>p.playerId==='fixture-0');v.online=mode!=='offline';v.lastSeenUtc=new Date(Date.now()-60000).toISOString();render();},mode);assert.equal(await p.locator('.directory-card[data-profile="fixture-0"] .profile-presence.'+mode).count(),1);assert.equal(await p.locator('#homeRoster [data-profile="fixture-0"] .profile-presence.'+mode).count(),1);}
assert.deepEqual(errors,[]);console.log('PASS roster avatar count, consistent presence styling/states, repeated same-profile status restoration, exact boss receipts, saved saga preview, no template/XSS, mobile layout.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
