/* Clearly labeled synthetic SLS/Nemesis fixtures; production browser functions, no game data. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.resolve(__dirname,'../../src/Sagas.Web/app.js'),'utf8');
const pick=(a,b)=>source.slice(source.indexOf(a),source.indexOf(b,source.indexOf(a)));
const code=[source.split('\n').find(line=>line.startsWith('function terrainTile(')),pick('function nemesisScore(','function renderLeaderboard('),pick('function slsOverlay(','function drawMap('),pick('function exploredPoint(','function visibleEvents(')].join('\n');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SAGAS_BROWSER_EXECUTABLE||(process.platform==='win32'?'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe':undefined)});try{const page=await browser.newPage();await page.setContent('<canvas id="canvas" width="256" height="256"></canvas><input id="slsLayer" type="checkbox" checked><div id="slsControls"></div><div id="mapHover"></div><div id="mapInspect" hidden></div>');const result=await page.evaluate(code=>{
 const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),view={width:256,height:256,x:0,z:0,scale:1},tileCache=new Map(),esc=String,number=String,date=String;
 const screen=(x,z)=>[x+128,128-z],world=(x,y)=>[x-128,128-y];const state={data:{sls:{installed:true,nemesisEnabled:true},players:[]},map:{cellSize:64,cells:[]},mapCells:new Map()};const visibleMarkers=()=>state.data.players;
 return eval(code+`\n(()=>{const results={};const zone={minX:0,maxX:64,minZ:0,maxZ:64,level:3,color:'#ff0000'};state.map.sls={installed:true,zoneScalingEnabled:true,overlayEnabled:true,aboveFog:true,opacity:1,outlineInset:2,zones:[zone]};
 const paint=()=>{ctx.clearRect(0,0,256,256);drawSls(ctx);return ctx.getImageData(0,0,256,256).data;};const alpha=(pixels,x,z)=>pixels[((128-z)*256+x+128)*4+3];
 const above=paint();results.above=alpha(above,2,40)>0;results.subtle=alpha(above,2,40)===51;state.map.sls.zones.push({...zone});results.overlap=alpha(paint(),2,40)===51;state.map.sls.zones.pop();state.map.sls.opacity=.1;results.lowerHostOpacity=Math.abs(alpha(paint(),2,40)-26)<=1;state.map.sls.opacity=0;results.zeroOpacity=alpha(paint(),2,40)===0;state.map.sls.opacity=1;results.outline=alpha(above,32,32)===0;results.level=slsZoneAt(20,20)?.level;mapHover(148,108);results.hover=$('mapHover').textContent==='Zone level 3';
 state.map.sls.aboveFog=false;results.hidden=alpha(paint(),2,40)===0&&slsZoneAt(20,20)===null;
 const raw=new Uint8Array(16*16*4);for(let z=8;z<16;z++)for(let x=0;x<16;x++){const i=(z*16+x)*4;raw[i]=20;raw[i+3]=255;}const cell={x:0,z:0,terrainPixels:btoa(String.fromCharCode(...raw))};state.map.cells=[cell];state.mapCells.set('0,0',cell);const masked=paint();results.maskKnown=alpha(masked,2,40)>0;results.maskUnknown=alpha(masked,2,20)===0;results.hoverKnown=slsZoneAt(20,40)?.level===3;results.hoverUnknown=slsZoneAt(20,20)===null;zone.level=1;results.levelOne=slsZoneAt(20,40)===null;zone.level=3;
 $('slsLayer').checked=false;results.toggle=alpha(paint(),2,40)===0&&slsZoneAt(20,40)===null;$('slsLayer').checked=true;state.map.sls.overlayEnabled=false;paint();results.disabled=$('slsControls').hidden;state.map.sls=null;paint();results.absent=$('slsControls').hidden;
 const player={name:'Synthetic Viking',x:20,z:40,nemesisScore:42.5,utc:'synthetic timestamp'};results.score=nemesisScore(player)===42.5;results.scoreZero=nemesisScore({...player,nemesisScore:0})===0;state.data.players=[player];mapHover(148,88);results.playerHover=$('mapHover').textContent.includes('Nemesis 42.5');results.timestamp=nemesisText(player).includes('synthetic timestamp');state.data.sls.nemesisEnabled=false;results.noScore=nemesisText(player)==='';state.data.sls=null;results.noMods=nemesisText(player)==='';return results;})()`);
 },code);for(const [name,passed] of Object.entries(result))assert(passed,name);console.log('PASS '+Object.keys(result).length+' SLS outline, fog-alpha, level-hover, optional-mod and Nemesis UI regressions.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
