const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const p=await browser.newPage({viewport:{width:1600,height:1150}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('sagas.viewer','synthetic-development-token-only'));
await p.goto('http://127.0.0.1:9847/#journey/synthetic-scenes?world=synthetic-journey');await p.waitForFunction(()=>window.SagaJourney?.debug().points===3);assert.equal(await p.locator('#journeySceneTitle').textContent(),'Beneath the listening pines');const first=await p.locator('#journeyPassage').textContent();assert(first.includes('The first shapes'));
await p.locator('[data-journey-moment="1"]').click();assert.equal(await p.locator('#journeySceneTitle').textContent(),'When the thunder answered');assert((await p.locator('#journeyPassage').textContent()).includes('Eikthyr'));assert(!(await p.locator('#journeyPassage').textContent()).includes('The first shapes'));await p.waitForFunction(()=>document.querySelector('.journey-boss')?.naturalWidth>0);
const markers=await p.evaluate(()=>SagaJourney.debug().markers);assert(markers.find(m=>m.boss).radius>markers.find(m=>!m.boss).radius,'Boss scene is a larger marker');
await p.locator('[data-journey-moment="2"]').click();assert((await p.locator('#journeyPassage').textContent()).includes('forest still had teeth'));assert.equal(await p.locator('.journey-boss').count(),0);
await p.locator('#journeyToggle').click();assert((await p.locator('#journeyList').textContent()).includes('Astrid (synthetic)'));await p.locator('#closeAtlasTray').click();
await p.locator('[data-journey-moment="0"]').click();await p.locator('#journeyPlay').click();await p.waitForFunction(()=>document.querySelector('#journeySceneTitle').textContent==='When the thunder answered');await p.locator('#journeyPlay').click();assert((await p.locator('#journeyChapter').textContent()).includes(first));
await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('#journeyPage').screenshot({path:'../../TestingOutputs/saga-scenes-0336-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS scene-specific passages, boss emphasis/art, chapter consistency, playback changes, named saga list and mobile layout.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
