const {revealAtlas}=require('./atlas-controls.cjs');
// Synthetic local HTTP host, never production/world data.
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SAGAS_BROWSER_EXECUTABLE||(process.platform==='win32'?'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe':undefined)});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>sessionStorage.setItem('sagas.viewer','synthetic-development-token-only'));await page.goto('http://127.0.0.1:9847/');await page.waitForFunction(()=>mapPins.length===3&&!state.busy);let count=0;const check=(value,label)=>{assert(value,label);count++;};
 check(!await page.locator('#vikingColors').isChecked(),'Viking colors opt-in');check(await page.locator('[data-pin-owner]').count()===2,'Owner list names each shared Viking');
 await page.evaluate(()=>{state.busy=true;const a=state.data.players.find(p=>p.playerId==='fixture-0'),b=state.data.players.find(p=>p.playerId==='fixture-1');mapPins[0].sources.push({playerId:b.playerId,name:b.name,color:b.mapColor,iconId:''});mapPins.find(p=>p.personal).x=1800;mapPins.find(p=>p.personal).z=400;drawMap();});
 await revealAtlas(page,'icons');await page.locator('#personalPinsLayer').check();check(await page.evaluate(()=>visibleMapPins().some(p=>p.personal&&p.x===1800&&!exploredPoint(p.x,p.z))),'Personal pin visible above undiscovered fog');
 check(await page.evaluate(()=>pinSize({personal:false})===36&&pinSize({personal:true})===26),'Larger game icons with proportional personal icons');
 await revealAtlas(page,'icons');await page.locator('#vikingColors').check();check(await page.evaluate(()=>state.data.players.every(p=>vikingMapColor(p)===p.mapColor)),'Marker and name colors match persisted Viking color');
 await page.locator('.pin-owner-filter summary').click();await page.locator('[data-pin-owner="fixture-0"]').uncheck();check(await page.evaluate(()=>visibleMapPins().length===1&&visibleMapPins()[0].sources.length===1&&visibleMapPins()[0].playerId==='fixture-1'),'Hidden owner removed but shared location kept for other Viking');
 check(await page.evaluate(()=>state.map.cells.length>0&&visibleMarkers().length===2),'Icon filter independent of terrain and live markers');
 await page.locator('#noPinOwners').click();check(await page.evaluate(()=>visibleMapPins().length===0),'Hide all icons works');await page.locator('#allPinOwners').click();check(await page.evaluate(()=>visibleMapPins().length===3),'Show all restores icons');
 const time=await page.evaluate(()=>{const c={secondsToTransition:420,nextPhase:'night',running:true};return [clockCountdown(c,0),clockCountdown(c,3),clockCountdown({...c,nextPhase:'day'},10),clockCountdown(c,31),clockCountdown({...c,running:false},0),clockCountdown({...c,skipping:true},0)];});
 check(await page.evaluate(()=>{const original=Date.now,age=clockAge(receivedClock);try{Date.now=()=>original()+86400000;return Math.abs(clockAge(receivedClock)-age)<.1;}finally{Date.now=original;}}),'Client clock skew does not corrupt real countdown');
 check(time[0]==='Night in 7m 00s'&&time[1]==='Night in 6m 57s','Countdown uses real elapsed seconds');check(time[2]==='Day in 6m 50s','Correct dawn label');check(time[3]==='Clock update overdue','Stale clock stops extrapolation');check(time[4]==='World paused'&&time[5]==='Time skipping','Pause and sleep do not fabricate countdown');
 await page.evaluate(()=>{clockSnapshot={world:state.filter.world,day:42,fraction:.5,utc:new Date().toISOString(),secondsToTransition:420,nextPhase:'night',running:true};renderWorldClock();view.x=500;view.z=100;view.scale=.25;drawMap();});check((await page.locator('.clock-phase').textContent()).startsWith('Night in'),'Graphic replaces static phase with countdown');
 await page.locator('#atlas').screenshot({path:'.dev/map0319-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('#map').scrollIntoViewIfNeeded();await page.screenshot({path:'.dev/map0319-mobile.png'});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile fits');
 await page.locator('[data-pin-owner="fixture-0"]').uncheck();await page.reload();await page.waitForFunction(()=>mapPins.length===3&&!state.busy);check(await page.locator('#vikingColors').isChecked(),'Color preference persists');check(!await page.locator('[data-pin-owner="fixture-0"]').isChecked(),'Per-world hidden owners persist');
 check(errors.length===0,'No script errors: '+errors.join(';'));console.log('PASS '+count+' Viking colors, multi-owner pins, independent filters, personal fog and real-time countdown checks.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
