<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><LangVersion>latest</LangVersion><CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies><Nullable>enable</Nullable><AssemblyName>ValheimSagas</AssemblyName><GameManaged Condition="'$(GameManaged)' == ''">C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Managed</GameManaged><BepInExCore Condition="'$(BepInExCore)' == ''">C:/Users/mecra/AppData/Roaming/com.kesomannen.gale/valheim/profiles/Test/BepInEx/core</BepInExCore></PropertyGroup>
<ItemGroup><ProjectReference Include="../Sagas.Core/Sagas.Core.csproj"/><Reference Include="BepInEx"><HintPath>$(BepInExCore)/BepInEx.dll</HintPath><Private>false</Private></Reference><Reference Include="0Harmony"><HintPath>$(BepInExCore)/0Harmony.dll</HintPath><Private>false</Private></Reference><Reference Include="assembly_valheim"><HintPath>$(GameManaged)/assembly_valheim.dll</HintPath><Private>false</Private></Reference><Reference Include="assembly_utils"><HintPath>$(GameManaged)/assembly_utils.dll</HintPath><Private>false</Private></Reference><Reference Include="UnityEngine"><HintPath>$(GameManaged)/UnityEngine.dll</HintPath><Private>false</Private></Reference><Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManaged)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference><Reference Include="assembly_guiutils"><HintPath>$(GameManaged)/assembly_guiutils.dll</HintPath><Private>false</Private></Reference></ItemGroup>
<ItemGroup><Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(GameManaged)/UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference></ItemGroup>
<ItemGroup><Reference Include="UnityEngine.ParticleSystemModule"><HintPath>$(GameManaged)/UnityEngine.ParticleSystemModule.dll</HintPath><Private>false</Private></Reference></ItemGroup>
<ItemGroup><Reference Include="UnityEngine.IMGUIModule"><HintPath>$(GameManaged)/UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference><Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(GameManaged)/UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private></Reference></ItemGroup>
<ItemGroup><Reference Include="com.rlabrecque.steamworks.net"><HintPath>$(GameManaged)/com.rlabrecque.steamworks.net.dll</HintPath><Private>false</Private></Reference></ItemGroup>
<ItemGroup><Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(GameManaged)/UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference></ItemGroup>
</Project>
