using ValheimSagas;
using Newtonsoft.Json.Linq;
using System.Reflection;
using System.Security.Cryptography;
static class AnalyticsDeliveryChecks {
 public static void Run(string root,Action<bool,string> check){
  var dir=Path.Combine(root,"analytics");var web=Path.Combine(dir,"web");Directory.CreateDirectory(web);File.WriteAllText(Path.Combine(web,"app.js"),"fixture");var hash=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(Path.Combine(web,"app.js")))).ToLowerInvariant();File.WriteAllText(Path.Combine(web,"version.json"),new JObject{{"version","0.3.33"},{"appSha256",hash}}.ToString());
  using var service=new SagaService(new(){DataDirectory=dir,WebDirectory=web,World="world",ServerVersion="0.3.33",ListenPrefix=""});var store=service.Store;var now=DateTime.UtcNow;var all=new TimeWindow(DateTime.MinValue,DateTime.MaxValue);
  var p=new PlayerSnapshot{World="world",PlayerId="p",Name="Viking",ShareProfile=true,ShareMap=true,SharePosition=true,Online=true,Utc=now,LastSeenUtc=now,X=5,Z=5};store.Player(p);store.Explore(new(){World="world",PlayerId="p",Cells=new(){new(){X=0,Z=0}}});
  SagaEvent Ev(string id,DateTime utc)=>new(){World="world",Id=id,PlayerId="p",PlayerName="Viking",Utc=utc,Kind="kill",Name="Troll",X=5,Z=5,Contributors=new(){"p","hidden"}};
  store.AddEvent(Ev("one",now.AddDays(-2)));store.AddEvent(Ev("two",now));
  var method=typeof(SagaStore).GetMethod("AnalyticsHistory",BindingFlags.NonPublic|BindingFlags.Instance)!;object History()=>method.Invoke(store,new object[]{"world"})!;
  var first=History();check(ReferenceEquals(first,History()),"Retained history reused without repeated database deserialization");
  var state=JObject.FromObject(service.State("world",all));check((int)state["stats"]!["kills"]! ==2,"Cached statistics complete");check(state["events"]![0]!["Contributors"]!.Count()==1,"Display excludes private contributors");
  var lastDay=JObject.FromObject(service.State("world",new TimeWindow(now.AddDays(-1),now.AddSeconds(1))));check((int)lastDay["stats"]!["kills"]! ==1,"Exact time window applied afresh to cached history");
  p.ShareMap=false;store.Player(p);state=JObject.FromObject(service.State("world",all));check(state["events"]!.All(e=>e["X"]!.Type==JTokenType.Null),"Immediate map consent revocation hides cached coordinates");
  p.ShareMap=true;store.Player(p);state=JObject.FromObject(service.State("world",all));check(state["events"]!.All(e=>(float)e["X"]! ==5),"Projection never mutates cached coordinates");check(store.Events("world",all).All(e=>e.Contributors.Count==2),"Contributor filtering never mutates retained records");
  p.ShareProfile=false;store.Player(p);check((int)JObject.FromObject(service.State("world",all))["stats"]!["kills"]! ==0,"Immediate profile revocation filters cached history");p.ShareProfile=true;store.Player(p);
  store.AddEvent(Ev("three",now));var updated=(IReadOnlyList<SagaEvent>)History();check(!ReferenceEquals(first,updated),"Committed event publishes a new immutable history snapshot");check(ReferenceEquals(((IReadOnlyList<SagaEvent>)first)[0],updated[0]),"New events append without reparsing old history");check(((IReadOnlyList<SagaEvent>)first).Count==2,"Concurrent readers retain a stable old snapshot");check((int)JObject.FromObject(service.State("world",all))["stats"]!["kills"]! ==3,"New event counted immediately");
  store.ApplyRetention(now.AddMinutes(1),0,1);check((int)JObject.FromObject(service.State("world",all))["stats"]!["kills"]! ==2,"Retention invalidates cached history");
  store.AddEvent(new(){World="world",Id="pending-collect",Kind="collect",PlayerId="p",Utc=now,Provenance="late-drop",Amount=2});History();store.AddEvent(new(){World="world",Id="late-drop",Kind="drop",PlayerId="p",Utc=now,Provenance="late-drop",Amount=2});check(((IReadOnlyList<SagaEvent>)History()).Any(e=>e.Id=="pending-collect"&&e.Amount==2),"Pending collection reconciliation appends every committed record");
  var boot=JObject.FromObject(service.WorldState("world"));check(boot["stats"]==null&&boot["events"]==null,"World bootstrap has no statistics or history payload");check(boot["players"]!.Count()==1,"World bootstrap includes presence");
  store.Worlds();store.AddEvent(new(){World="other",Id="other",Kind="kill",Utc=now});check(store.Worlds().Contains("other"),"World index updated on event commit");store.Player(new(){World="third",PlayerId="new"});check(store.Worlds().Contains("third"),"World index updated on new profile");
  var version=JObject.FromObject(service.VersionInfo());check(!(bool)version["mismatch"]!,"Matching runtime and website manifest verified");check((string)version["websiteHash"]! ==hash,"Actual served JavaScript fingerprint returned");
  using var mismatch=new SagaService(new(){DataDirectory=Path.Combine(root,"mismatch"),WebDirectory=web,ServerVersion="0.3.34",ListenPrefix=""});check((bool)JObject.FromObject(mismatch.VersionInfo())["mismatch"]!,"Mixed plugin website versions detected");
  foreach(var invalid in new[]{"[]","{bad","{\"version\":{},\"appSha256\":[]}","{\"version\":\"0.3.33\",\"appSha256\":\"bad\"}",new string(' ',5000)}){File.WriteAllText(Path.Combine(web,"version.json"),invalid);using var malformed=new SagaService(new(){DataDirectory=Path.Combine(root,"invalid-version-"+Guid.NewGuid().ToString("N")),WebDirectory=web,ServerVersion="0.3.33",ListenPrefix=""});var report=JObject.FromObject(malformed.VersionInfo());check((bool)report["mismatch"]!,"Malformed manifest yields safe mismatch instead of HTTP500");check((string)report["websiteHash"]! ==hash,"Malformed manifest still fingerprints actual website");}
  File.WriteAllText(Path.Combine(web,"version.json"),new JObject{{"version","0.3.33"},{"appSha256",hash}}.ToString());
  File.WriteAllText(Path.Combine(web,"app.js"),"stale bytes");using var stale=new SagaService(new(){DataDirectory=Path.Combine(root,"stale"),WebDirectory=web,ServerVersion="0.3.33",ListenPrefix=""});check((bool)JObject.FromObject(stale.VersionInfo())["mismatch"]!,"Stale asset behind matching manifest detected");
  var warnings=new System.Collections.Concurrent.ConcurrentQueue<string>();var probe=new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback,0);probe.Start();int port=((System.Net.IPEndPoint)probe.LocalEndpoint).Port;probe.Stop();
  using var running=new SagaService(new(){DataDirectory=Path.Combine(root,"startup-version"),WebDirectory=web,ServerVersion="0.3.33",ListenPrefix=$"http://127.0.0.1:{port}/",Log=message=>warnings.Enqueue(message)});running.Start();running.Start();using var http=new HttpClient{BaseAddress=new Uri($"http://127.0.0.1:{port}/"),Timeout=TimeSpan.FromSeconds(10)};check(http.GetAsync("api/health").GetAwaiter().GetResult().IsSuccessStatusCode,"Mismatched website remains available with explicit startup warning");check(warnings.Count(message=>message.StartsWith("WARNING: Sagas website"))==1,"Startup asset mismatch warning emitted exactly once even if Start repeated");check(warnings.Any(message=>message.Contains("complete matching Sagas package")&&message.Contains("preserve configuration")),"Host warning explains safe complete-package replacement");

 }
}
