using System.Net;
using System.Net.Sockets;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ValheimSagas;
static class PersonalLoreChecks{
 public static async Task Run(string root,Action<bool,string> check){var dir=Path.Combine(root,"personal-lore");var probe=new TcpListener(IPAddress.Loopback,0);probe.Start();var port=((IPEndPoint)probe.LocalEndpoint).Port;probe.Stop();const string secret="synthetic-openrouter-secret-do-not-send";using(var service=new SagaService(new(){DataDirectory=dir,World="w",ListenPrefix=$"http://127.0.0.1:{port}/",RequireViewerToken=false})){service.Store.Player(new(){World="w",PlayerId="owner",Name="Owner"});service.Store.Player(new(){World="w",PlayerId="other",Name="Other"});var token=service.Store.RotatePlayerLogin("w","owner");service.Start();using var http=new HttpClient{BaseAddress=new Uri($"http://127.0.0.1:{port}/")};check((await http.GetAsync("api/lore-settings")).StatusCode==HttpStatusCode.Forbidden,"Anonymous cannot read storyteller settings");http.DefaultRequestHeaders.Authorization=new("Bearer",token);
 async Task<JObject> Post(object body,int expected=200){var r=await http.PostAsync("api/lore-settings",new StringContent(JsonConvert.SerializeObject(body),Encoding.UTF8,"application/json"));check((int)r.StatusCode==expected,"Personal lore response "+expected);return JObject.Parse(await r.Content.ReadAsStringAsync());}
 var result=await Post(new{key=secret,active="Saga",presets=new[]{new LorePreset{Name="Saga",Route="@preset/my-story"}}});check((bool)result["hasKey"]!&&!(bool)result["hostEnabled"]!,"Key stored but missing host key keeps generation disabled");check(!result.ToString().Contains(secret)&&service.Store.PersonalLore("w","owner").Key=="configured","Settings only disclose key presence");check(service.Store.PersonalLore("w","owner",true).Key==secret,"Encrypted key round-trips for server worker");check(service.Store.PersonalLore("w","other",true).Key=="","Other character has no access to owner key");
 await Post(new{active="Paid",presets=new[]{new LorePreset{Name="Paid",Route="vendor/paid"}}},400);await Post(new{active="Paid",presets=new[]{new LorePreset{Name="Paid",Route="vendor/paid",AllowPaid=true,MaxPrice=0}}},400);await Post(new{active="Paid",presets=new[]{new LorePreset{Name="Paid",Route="vendor/paid",AllowPaid=true,MaxPrice=1,DailyRequests=2}}});check(service.Store.PersonalLore("w","owner",true).Key==secret,"Omitted key preserves encrypted credential");await Post(new{playerId="other",active="",presets=Array.Empty<LorePreset>()},400);await Post(new{active="x",presets=new[]{new LorePreset{Name="x",Route="https://example.invalid"}}},400);
 check(service.Store.ReservePersonalLore("w","owner",2)&&service.Store.ReservePersonalLore("w","owner",2)&&!service.Store.ReservePersonalLore("w","owner",2),"Personal attempts enforce independent durable daily bound");service.Store.DeferLore("w","owner");check(!service.Store.LoreReady("w","owner"),"Failed generation has durable retry delay");
 }
 check(!Encoding.UTF8.GetString(File.ReadAllBytes(Path.Combine(dir,"sagas.db"))).Contains(secret),"Database has no plaintext personal API key");using(var store=new SagaStore(dir)){check(store.PersonalLore("w","owner",true).Key==secret,"Encrypted key survives restart");check(!store.ReservePersonalLore("w","owner",2)&&!store.LoreReady("w","owner"),"Budgets and retry delay survive restart");store.SavePersonalLore("w","owner",new(){ClearKey=true});check(store.PersonalLore("w","owner",true).Key=="","Explicit key removal revokes future personal generation");}
 }
}
