using ValheimSagas;
// Explicit synthetic evidence for repeatable journey UI checks. Never packaged.
static class JourneyFixture {
 public static void Add(SagaService service){
  const string world="synthetic-journey";var now=DateTime.UtcNow;
  service.Store.WorldName(world,"Synthetic saga journey");
  service.UpdatePlayer(new(){World=world,PlayerId="story-astrid",Name="Astrid (synthetic)",ShareProfile=true,ShareMap=true,Online=true});
  var cells=new List<MapCell>();for(int x=-14;x<=14;x++)for(int z=-12;z<=12;z++)cells.Add(new(){X=x,Z=z,Biome=x<0?"Meadows":"BlackForest"});service.Explore(new(){World=world,PlayerId="story-astrid",Cells=cells,Imported=true});
  var names=new[]{"Greydwarf","Greydwarf Brute","Eikthyr","Skeleton","Troll"};var ids=new List<string>();
  for(int i=0;i<5;i++){var id="synthetic-journey-"+i;ids.Add(id);service.TryEvent(new(){Id=id,World=world,PlayerId="story-astrid",PlayerName="Astrid (synthetic)",Name=names[i],Prefab=names[i],Kind="kill",Boss=i==2,Biome=i<2?"Meadows":"BlackForest",Utc=now.AddMinutes(-25+i*5),X=-520+i*250,Z=-430+i*200,Stars=i==4?2:0,Source="synthetic"});}
  service.Store.Chapter(new(){Id="synthetic-thunder",World=world,PlayerId="story-astrid",Title="Where the thunder answered",Text="Rain hissed against the shield. Beneath the pines, Astrid held her ground as thunder found its voice.\n\nThe forest had been quiet when she entered it. Now every branch trembled, and the light between the trees belonged to the storm. She raised her shield and took one step forward.\n\nWhen the thunder faded, it left a different silence. Astrid stood beneath the dripping boughs, listening to the rain return.\n\nSynthetic narrative for interface testing; these are not recorded player adventures.",Model="fixture/synthetic-story",Utc=now,FromUtc=now.AddMinutes(-30),ToUtc=now,EventIds=ids,Participants=new(){new(){PlayerId="story-astrid",Name="Astrid (synthetic)"}},Facts=new(){"Five synthetic event locations for journey playback tests."}});
  var passages=new[]{"The first shapes moved between the trees before Astrid heard them. She raised her shield beneath the dripping branches, and the quiet forest became a place of hard edges and watchful shadows.","Then the thunder answered. Eikthyr stood in the telling like a storm given antlers, and the clash left a new silence beneath the boughs. The recorded victory would endure; the skald would remember the light.","Beyond that silence, the forest still had teeth. A skeleton and a troll marked the remaining pages of this journey. Astrid's tale did not end with the thunder: it went on beneath the pines."};
  service.Store.Chapter(new(){Id="synthetic-scenes",World=world,PlayerId="story-astrid",Title="Thunder beneath the boughs",Text=string.Join("\n\n",passages),Model="fixture/synthetic-scenes",Utc=now.AddSeconds(1),FromUtc=now.AddMinutes(-30),ToUtc=now,EventIds=ids,Scenes=new(){new(){Title="Beneath the listening pines",Text=passages[0],EventIds=ids.Take(2).ToList()},new(){Title="When the thunder answered",Text=passages[1],EventIds=new(){ids[2]}},new(){Title="The forest still had teeth",Text=passages[2],EventIds=ids.Skip(3).ToList()}},Facts=new(){"Illustrative synthetic story and events for interface testing; not a real adventure."}});
 }
}
