using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using LiteDB;
namespace ValheimSagas;

// Overview pixels never expose an unexplored subpixel. The separate exact bit mask
// preserves personal fog and hit testing even when the displayed terrain is coarse.
public sealed class MapOverviewCell {
 public int X {get;set;} public int Z {get;set;} public string Biome {get;set;}="";public float Height {get;set;}
 public string TerrainPixels {get;set;}="";public string ExplorationMask {get;set;}="";
 internal static MapOverviewCell From(MapCell cell,int side=4){
  var bytes=TerrainTile.Decode(cell.TerrainPixels);int source=bytes?.Length==TerrainTile.RenderedByteCount?64:16;var mask=new byte[512];var pixels=new byte[side*side*4];
  for(int z=0;z<64;z++)for(int x=0;x<64;x++){int p=z*64+x;if(string.IsNullOrEmpty(cell.TerrainPixels)||bytes!=null&&bytes[((z*source/64)*source+x*source/64)*4+3]==255)mask[p>>3]|=(byte)(1<<(p&7));}
  if(bytes!=null)for(int z=0;z<side;z++)for(int x=0;x<side;x++){long r=0,g=0,b=0;int n=0;for(int py=z*64/side;py<(z+1)*64/side;py++)for(int px=x*64/side;px<(x+1)*64/side;px++){int p=py*64+px;if((mask[p>>3]&(1<<(p&7)))==0)continue;int at=((py*source/64)*source+px*source/64)*4;r+=bytes[at];g+=bytes[at+1];b+=bytes[at+2];n++;}if(n>0){int at=(z*side+x)*4;pixels[at]=(byte)(r/n);pixels[at+1]=(byte)(g/n);pixels[at+2]=(byte)(b/n);pixels[at+3]=255;}}
  return new MapOverviewCell{X=cell.X,Z=cell.Z,Biome=cell.Biome,Height=cell.Height,TerrainPixels=bytes==null?"":Convert.ToBase64String(pixels),ExplorationMask=Convert.ToBase64String(mask)};
 }
 internal static MapOverviewCell Union(IEnumerable<MapOverviewCell> source,int side=4){var cells=source.ToArray();var first=cells[0];var result=new MapOverviewCell{X=first.X,Z=first.Z,Biome=first.Biome,Height=first.Height};var mask=new byte[512];var pixels=new byte[side*side*4];bool legacy=false;
  foreach(var c in cells){var m=Convert.FromBase64String(c.ExplorationMask);for(int i=0;i<512;i++)mask[i]|=m[i];if(c.TerrainPixels.Length==0){legacy=true;continue;}var b=Convert.FromBase64String(c.TerrainPixels);for(int i=0;i<pixels.Length;i+=4)if(b[i+3]==255)Array.Copy(b,i,pixels,i,4);}
  for(int z=0;z<side;z++)for(int x=0;x<side;x++){bool full=true;for(int py=z*64/side;py<(z+1)*64/side&&full;py++)for(int px=x*64/side;px<(x+1)*64/side;px++){int p=py*64+px;if((mask[p>>3]&(1<<(p&7)))==0){full=false;break;}}if(!full)Array.Clear(pixels,(z*side+x)*4,4);}
  result.TerrainPixels=legacy?"":Convert.ToBase64String(pixels);result.ExplorationMask=Convert.ToBase64String(mask);return result;
 }
 internal static bool Known(byte[] mask,int x,int z){int p=z*64+x;return x>=0&&x<64&&z>=0&&z<64&&(mask[p>>3]&(1<<(p&7)))!=0;}
}
public sealed partial class SagaStore {
 void InitializeMapIndex(){db.GetCollection("mapOverview").EnsureIndex("revision");db.GetCollection("mapOverview").EnsureIndex("world");db.GetCollection("mapOverview").EnsureIndex("imported");}
 long MapRevisionUnsafe()=>db.GetCollection("meta").FindById("mapRevision")?["value"].AsInt64??0;
 public long MapRevision {get{lock(gate)return MapRevisionUnsafe();}}
 void IndexMapCell(string id,string world,string player,MapCell cell,bool imported){long rev=MapRevisionUnsafe()+1;var row=Wrap(id,world,player,MapOverviewCell.From(cell),DateTime.UtcNow);row["revision"]=rev;row["x"]=cell.X;row["z"]=cell.Z;row["imported"]=imported;db.GetCollection("mapOverview").Upsert(row);db.GetCollection("meta").Upsert(new BsonDocument{{"_id","mapRevision"},{"value",rev}});}
 // A legacy world is converted in bounded batches, never in the startup or state poll.
 public bool MigrateMapPage(){lock(gate){var meta=db.GetCollection("meta");var progress=meta.FindById("mapOverviewMigration");if(progress!=null&&progress["done"].AsBoolean)return false;string after=progress?["after"].AsString??"";var rows=db.GetCollection("cells").Find(Query.GT("_id",after),0,128).ToArray();db.BeginTrans();try{foreach(var row in rows){if(db.GetCollection("mapOverview").FindById(row["_id"])==null)IndexMapCell(row["_id"].AsString,row["world"].AsString,row["player"].AsString,Read<MapCell>(row),row["imported"].AsBoolean);after=row["_id"].AsString;}bool more=rows.Length==128;meta.Upsert(new BsonDocument{{"_id","mapOverviewMigration"},{"after",after},{"done",!more}});db.Commit();return more;}catch{db.Rollback();throw;}}}
 public (List<MapOverviewCell> Cells,long Cursor,bool More) MapPage(string world,HashSet<string> owners,long cursor,int limit=256){lock(gate){if(limit<1||limit>256)throw new ArgumentException("Map page limit must be 1–256.");var rows=db.GetCollection("mapOverview").Find(Query.GT("revision",cursor),0,limit).ToArray();var keys=rows.Where(r=>r["world"].AsString==world&&owners.Contains(r["player"].AsString)).Select(r=>(X:r["x"].AsInt32,Z:r["z"].AsInt32)).Distinct();var cells=new List<MapOverviewCell>();foreach(var key in keys){var values=owners.Select(p=>db.GetCollection("mapOverview").FindById(Key(world,p,key.X.ToString(),key.Z.ToString()))).Where(r=>r!=null).Select(Read<MapOverviewCell>).ToArray();if(values.Length>0)cells.Add(MapOverviewCell.Union(values));}return(cells,rows.Length==0?cursor:rows.Last()["revision"].AsInt64,rows.Length==limit);}}
 public List<MapOverviewCell> MapDetail(string world,HashSet<string> owners,IEnumerable<(int X,int Z)> keys,int side){if(side!=16&&side!=64)throw new ArgumentException("Map detail side must be 16 or 64.");var positions=keys.Distinct().ToArray();if(positions.Length>64||positions.Any(k=>Math.Abs((long)k.X)>313||Math.Abs((long)k.Z)>313))throw new ArgumentException("Map detail accepts at most 64 valid tile coordinates.");lock(gate){var result=new List<MapOverviewCell>();foreach(var key in positions){var values=owners.Select(p=>db.GetCollection("cells").FindById(Key(world,p,key.X.ToString(),key.Z.ToString()))).Where(r=>r!=null).Select(Read<MapCell>).ToArray();if(values.Length>0){var cell=TerrainTile.Union(values);result.Add(MapOverviewCell.Union(new[]{MapOverviewCell.From(cell,side)},side));}}return result;}}
 public bool KnownPoint(string world,HashSet<string> owners,float x,float z){int tx=(int)Math.Floor(x/64),tz=(int)Math.Floor(z/64);lock(gate){foreach(var p in owners){string id=Key(world,p,tx.ToString(),tz.ToString());var row=db.GetCollection("mapOverview").FindById(id);if(row!=null){if(MapOverviewCell.Known(Convert.FromBase64String(Read<MapOverviewCell>(row).ExplorationMask),(int)Math.Floor(x-tx*64),(int)Math.Floor(z-tz*64)))return true;}else{row=db.GetCollection("cells").FindById(id);if(row!=null&&TerrainTile.Known(Read<MapCell>(row),x,z))return true;}}return false;}}
 string maskCacheScope="";long maskCacheRevision=-1;readonly Dictionary<(int X,int Z),MapOverviewCell> maskCache=new Dictionary<(int X,int Z),MapOverviewCell>();
 public bool MapImported(string world,HashSet<string> owners){lock(gate)return db.GetCollection("mapOverview").Find(Query.EQ("imported",true)).Any(r=>r["world"].AsString==world&&owners.Contains(r["player"].AsString));}
 public (List<MapOverviewCell> Cells,bool Imported) MapMasks(string world,HashSet<string> owners){lock(gate){string scope=Key(new[]{world}.Concat(owners.OrderBy(x=>x,StringComparer.Ordinal)).ToArray());long revision=MapRevisionUnsafe();if(scope!=maskCacheScope){maskCache.Clear();maskCacheScope=scope;maskCacheRevision=-1;}
  if(maskCacheRevision!=revision){var query=maskCacheRevision<0?Query.EQ("world",world):Query.GT("revision",maskCacheRevision);var coordinates=db.GetCollection("mapOverview").Find(query).Where(r=>r["world"].AsString==world&&owners.Contains(r["player"].AsString)).Select(r=>(X:r["x"].AsInt32,Z:r["z"].AsInt32)).Distinct().ToArray();foreach(var position in coordinates){var mask=new byte[512];foreach(var owner in owners){var row=db.GetCollection("mapOverview").FindById(Key(world,owner,position.X.ToString(),position.Z.ToString()));if(row==null)continue;var bytes=Convert.FromBase64String(Read<MapOverviewCell>(row).ExplorationMask);for(int i=0;i<512;i++)mask[i]|=bytes[i];}maskCache[position]=new MapOverviewCell{X=position.X,Z=position.Z,ExplorationMask=Convert.ToBase64String(mask)};}maskCacheRevision=revision;}
  return(maskCache.Values.ToList(),MapImported(world,owners));}}

}
public sealed partial class SagaService {
 readonly string mapInstance=Guid.NewGuid().ToString("N");
 HashSet<string> MapOwners(string world,HashSet<string>? selected)=>new HashSet<string>(store.Players(world).Where(p=>p.ShareMap&&(selected==null||selected.Contains(p.PlayerId))).Select(p=>p.PlayerId));
 string MapScope(string world,HashSet<string> owners){using(var sha=SHA256.Create())return mapInstance+Convert.ToBase64String(sha.ComputeHash(Encoding.UTF8.GetBytes(world+"\n"+string.Join("\n",owners.OrderBy(x=>x,StringComparer.Ordinal)))));}
 public object MapStream(string world,HashSet<string>? selected=null,string? scope=null,string? cursor=null){var owners=MapOwners(world,selected);string current=MapScope(world,owners);bool reset=current!=scope;long revision=0;if(!reset&&(!long.TryParse(cursor,NumberStyles.None,CultureInfo.InvariantCulture,out revision)||revision<0||revision>store.MapRevision)){reset=true;revision=0;}bool migrating=store.MigrateMapPage();var page=store.MapPage(world,owners,revision);return new{scope=current,cursor=page.Cursor.ToString(CultureInfo.InvariantCulture),reset,more=migrating||page.More,cells=page.Cells,cellSize=64};}
 public object MapDetail(string world,HashSet<string>? selected,string keys,int side=64){var positions=new List<(int X,int Z)>();if(keys.Length>2048)throw new ArgumentException("Too many map detail keys.");foreach(var key in keys.Split(new[]{';'},StringSplitOptions.RemoveEmptyEntries)){var parts=key.Split(',');if(parts.Length!=2||!int.TryParse(parts[0],NumberStyles.Integer,CultureInfo.InvariantCulture,out var x)||!int.TryParse(parts[1],NumberStyles.Integer,CultureInfo.InvariantCulture,out var z))throw new ArgumentException("Invalid map tile coordinate.");positions.Add((x,z));}var owners=MapOwners(world,selected);return new{scope=MapScope(world,owners),cells=store.MapDetail(world,owners,positions,side),cellSize=64};}
 readonly object mapMetaGate=new object();string mapMetaKey="";object? mapMetaCache;
 public object MapMeta(string world,HashSet<string>? selected=null){var owners=MapOwners(world,selected);var sls=ActiveSls(world);string scope=MapScope(world,owners),key=scope+":"+store.MapRevision+":"+sls.Utc.Ticks;lock(mapMetaGate){if(mapMetaKey==key&&mapMetaCache!=null)return mapMetaCache;bool needsMasks=sls.Installed&&sls.ZoneScalingEnabled&&sls.OverlayEnabled&&!sls.AboveFog;var data=needsMasks?store.MapMasks(world,owners):(Cells:new List<MapOverviewCell>(),Imported:store.MapImported(world,owners));var masks=data.Cells.ToDictionary(c=>(c.X,c.Z),c=>Convert.FromBase64String(c.ExplorationMask));bool Visible(SlsZone zone){for(int z=(int)Math.Floor(zone.MinZ/64);z<Math.Ceiling(zone.MaxZ/64);z++)for(int x=(int)Math.Floor(zone.MinX/64);x<Math.Ceiling(zone.MaxX/64);x++){if(!masks.TryGetValue((x,z),out var mask))continue;for(int pz=Math.Max(0,(int)Math.Floor(zone.MinZ-z*64));pz<Math.Min(64,(int)Math.Ceiling(zone.MaxZ-z*64));pz++)for(int px=Math.Max(0,(int)Math.Floor(zone.MinX-x*64));px<Math.Min(64,(int)Math.Ceiling(zone.MaxX-x*64));px++)if(MapOverviewCell.Known(mask,px,pz))return true;}return false;}var zones=sls.Installed&&sls.ZoneScalingEnabled&&sls.OverlayEnabled?sls.Zones.Where(z=>sls.AboveFog||Visible(z)).ToList():new List<SlsZone>();mapMetaCache=new{scope,sls=new{sls.Installed,sls.NemesisEnabled,sls.ZoneScalingEnabled,sls.OverlayEnabled,sls.AboveFog,sls.Opacity,sls.OutlineInset,sls.Utc,zones},imported=data.Imported,label="Voluntarily shared known map; imported discoveries predate tracking. Runtime-rendered Valheim map with personal fog."};mapMetaKey=key;return mapMetaCache;}}
}
