/* Recorded saga journeys. Independent feed and transparent animation surface;
   the terrain canvas is never repainted just to move the replay arrow. */
'use strict';
(() => {
 const atlas=$('atlas'),home=document.createComment('World atlas home');atlas.before(home);
 const layout=atlas.querySelector('.atlas-layout'),frame=atlas.querySelector('.map-frame');
 const paths={quill:'M5 20 8 12 18 3 21 3 21 6 12 16 5 20 M8 12 12 16 M5 20 3 22',sword:'M4 3 8 4 20 19 M3 7 7 3 M4 20 19 4 21 3 20 6 M3 17 7 21',gem:'M3 8 8 3 16 3 21 8 12 22 3 8 M3 8 21 8 M8 3 9 8 12 22 15 8 16 3',fire:'M12 2C15 9 21 11 19 17C17 24 5 23 4 16C3 12 8 9 8 9C7 16 11 17 12 13C14 9 12 2 12 2 M5 23 20 20 M4 20 20 23',antler:'M12 22 12 12 M12 16 7 12 5 4 M7 12 2 9 2 4 M6 8 9 5 9 1 M12 16 17 12 19 4 M17 12 22 9 22 4 M18 8 15 5 15 1',skull:'M6 15C-3 0 26-1 19 15L17 16 17 21 7 21 7 16Z M8 10 9 11 M15 10 16 11 M11 16 13 16',flag:'M5 23V3C10-1 15 8 21 3V14C15 19 10 10 5 14'};
 const glyph=kind=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[kind]||paths.quill}"/></svg>`;
 const icon=m=>m?.boss||m?.nemesisBoss?'antler':m?.kind==='collect'||m?.kind==='drop'?'gem':m?.kind==='death'?'skull':m?.kind==='kill'?'sword':'fire';
 const corner='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M1 47V1H47 M6 38V6H38 M1 19L19 1 19 12 12 19 1 19 M6 30L30 6 M9 23L23 9 23 23 9 23 M1 40L6 35 M35 6L40 1"/></svg>';
 const border='<div class="journey-ornament" aria-hidden="true">'+['nw','ne','se','sw'].map(c=>'<i class="'+c+'">'+corner+'</i>').join('')+'</div>';
 const toggle=document.createElement('button');toggle.type='button';toggle.id='journeyToggle';toggle.dataset.atlasTray='sagas';toggle.innerHTML=glyph('quill')+'<span>Sagas</span>';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','atlas-sagas');atlas.querySelector('.atlas-tools').append(toggle);
 const tray=document.createElement('section');tray.id='atlas-sagas';tray.hidden=true;tray.dataset.atlasPanel='';tray.innerHTML='<p class="muted">Follow chapters through their shared, explored moments. Independent of statistics filters; follows Shared maps.</p><label class="check"><input id="journeyLayer" type="checkbox">Saga chapter markers</label><p id="journeyFeedStatus" role="status"></p><div id="journeyList"></div><button id="journeyMore" type="button" hidden>Older chapters</button>';$('atlasTray').append(tray);
 const surface=document.createElement('canvas');surface.id='journeySurface';surface.setAttribute('aria-hidden','true');frame.append(surface);const paint=surface.getContext('2d');
 const dock=document.createElement('div');dock.id='journeyDock';dock.hidden=true;dock.innerHTML='<div class="journey-transport"><button id="journeyPlay" type="button" aria-label="Play journey">▶</button><div class="journey-progress"><label for="journeyScrub">Journey replay <span id="journeyCount"></span></label><input id="journeyScrub" type="range" min="0" max="1" step="0.01" value="0" aria-label="Journey moment"></div><label class="journey-speed"><span class="journey-sr">Replay speed</span><select id="journeySpeed"><option value="1">1×</option><option value="2">2×</option><option value="0.5">½×</option></select></label><label class="check"><input id="journeyFollow" type="checkbox" checked>Follow journey</label><button id="journeyFit" type="button" title="Fit journey">↗</button></div><small>Connects recorded moments, not exact footsteps.</small>';frame.append(dock);
 const panel=document.createElement('aside');panel.id='journeyStory';panel.hidden=true;panel.setAttribute('aria-label','Selected saga');layout.append(panel);frame.insertAdjacentHTML('beforeend',border);
 let responseKey='',enabled=false,rows=[],next='',active=null,allPoints=[],selectedTrack='',points=[],position=0,playing=false,raf=0,last=0,epoch=0,context='',due=0,busy=false,detailBusy=false,detailId='',hits=[],pausedByVisibility=false;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const visible=()=>['world','journey'].includes(document.body.dataset.page);
 const currentContext=()=>mapContext()+'|'+privacySignature(state.data?.players);
 function pause(){playing=false;cancelAnimationFrame(raf);raf=0;last=0;$('journeyPlay').textContent='▶';$('journeyPlay').setAttribute('aria-label','Play journey');}
 function reset(){epoch++;load.serial++;responseKey='';context=currentContext();rows=[];next='';active=null;allPoints=[];selectedTrack='';points=[];detailId='';due=0;busy=detailBusy=false;pause();panel.hidden=dock.hidden=true;panel.textContent='';layout.classList.remove('with-journey');$('journeyList').textContent='';$('journeyChapter').textContent='';$('journeyTitle').textContent='A saga journey';draw();}
 function showTray(){openAtlasTray('sagas');toggle.setAttribute('aria-expanded','true');$('atlasTrayTitle').textContent='Saga journeys';}
 toggle.onclick=()=>{if(!$('atlasTray').hidden&&!tray.hidden){closeAtlasTray();toggle.setAttribute('aria-expanded','false');return;}showTray();enabled=true;$('journeyLayer').checked=true;refresh(true);draw();};
 $('journeyLayer').onchange=()=>{enabled=$('journeyLayer').checked;if(!enabled){pause();panel.hidden=dock.hidden=true;layout.classList.remove('with-journey');}else{refresh(true);if(active)render();}draw();};
 function owner(c){return c.scope==='server'?'Server saga':state.data?.players?.find(p=>p.playerId===c.playerId)?.name||c.participants?.find(p=>p.playerId===c.playerId)?.name||'Viking saga';}
 function list(){const box=$('journeyList');box.innerHTML=rows.map((r,i)=>'<button type="button" data-journey-row="'+i+'">'+glyph('quill')+'<span><strong>'+esc(r.chapter.title)+'</strong><span class="journey-owner">'+esc(owner(r.chapter))+'</span><small>'+esc(date(r.chapter.utc))+(r.anchor?'':' · No shared locations')+'</small></span></button>').join('');$('journeyMore').hidden=!next;$('journeyFeedStatus').textContent=rows.length?'Select a chapter to reveal its journey.':'No shared AI chapters yet. Sagas begin when OpenRouter is configured and adventures are recorded.';}
 async function refresh(force=false,more=false){if(!visible()||!state.data||!state.accessReady||(!state.token&&!state.publicViewing))return;if(context!==currentContext())reset();if(document.body.dataset.page==='journey'&&!chooseRouteWorld())return;if(!enabled&&document.body.dataset.page!=='journey')return;if(busy||(!force&&Date.now()<due))return;const captured=context,serial=epoch;busy=true;due=Date.now()+15000;try{const d=await api('/api/saga-journeys',{world:state.filter.world,players:state.mapPlayers.join(','),...(more?{before:next}:{})});if(serial!==epoch||captured!==currentContext())return;rows=more?[...rows,...d.chapters].slice(-96):d.chapters||[];next=d.next||'';list();draw();if(active)load(active.id,false);else if(document.body.dataset.page==='journey')route();}catch{if(serial===epoch)$('journeyFeedStatus').textContent='Saga journeys unavailable. Open Sagas to retry.';}finally{if(serial===epoch)busy=false;}}
 $('journeyMore').onclick=()=>refresh(true,true);$('journeyList').onclick=e=>{const b=e.target.closest('[data-journey-row]');if(b)load(rows[Number(b.dataset.journeyRow)].chapter.id,true);};
 async function load(id,fit=false){if(!id||!state.filter.world)return;if(context!==currentContext())reset();const captured=context,serial=epoch,routeHash=location.hash;if(detailBusy&&detailId===id)return;detailId=id;detailBusy=true;const request=++load.serial;try{const d=await api('/api/saga-journey',{world:state.filter.world,chapter:id,players:state.mapPlayers.join(',')});if(serial!==epoch||request!==load.serial||captured!==currentContext()||routeHash!==location.hash)return;if(!d.chapter){panel.textContent='';active=null;responseKey='';allPoints=[];points=[];pause();panel.hidden=dock.hidden=true;layout.classList.remove('with-journey');$('journeyChapter').textContent='This chapter is unavailable or its participants no longer share it.';$('journeyTitle').textContent='Chapter unavailable';draw();return;}const key=JSON.stringify(d);if(key===responseKey){if(fit)fitJourney();return;}responseKey=key;const changed=active?.id!==id,oldPoint=points[Math.floor(position)]?.id,oldFraction=position%1;active=d.chapter;allPoints=d.moments||[];if(changed)selectedTrack='';points=selectedTrack?allPoints.filter(m=>m.playerId===selectedTrack):allPoints;active.truncated=d.truncated;if(changed){pause();position=0;}else if(oldPoint){position=Math.min(points.length-1,Math.max(0,points.findIndex(m=>m.id===oldPoint))+oldFraction);}enabled=true;$('journeyLayer').checked=true;if(changed)openAtlasTray('');render();if(fit||changed)requestAnimationFrame(()=>requestAnimationFrame(fitJourney));draw();}catch{if(serial===epoch&&request===load.serial){$('journeyFeedStatus').textContent='This journey could not load. Select it to retry.';if(document.body.dataset.page==='journey')$('journeyChapter').innerHTML='<p>Journey unavailable. <button id="retryJourney">Try again</button></p>';$('retryJourney')?.addEventListener('click',()=>load(id,true));}}finally{if(request===load.serial)detailBusy=false;}}load.serial=0;
 function art(m){const names={Meadows:'meadows',BlackForest:'black-forest',Swamp:'swamp',Mountain:'mountain',Mountains:'mountain',Plains:'plains',Mistlands:'mistlands',AshLands:'ashlands',Ashlands:'ashlands',DeepNorth:'deep-north'},boss=Object.hasOwn(trophyArt,m?.prefab)?trophyArt[m.prefab]:'';return {biome:names[m?.biome]||({Eikthyr:'meadows',gd_king:'black-forest',Bonemass:'swamp',Dragon:'mountain',GoblinKing:'plains',SeekerQueen:'mistlands',Fader:'ashlands',FrozenKing_p3:'deep-north'}[m?.prefab])||'meadows',boss:boss?'/bosses/'+boss+'.webp':''};}
 function scene(m){const a=art(m);return '<div class="journey-art" aria-hidden="true"><img class="journey-landscape" src="/biomes/grounded/'+a.biome+'-1920.webp" alt="">'+(a.boss?'<img class="journey-boss" src="'+a.boss+'" alt="">':'')+'</div>';}
 function record(m){if(!m)return 'No shared locations remain for this chapter.';return (m.nemesisBoss?'Nemesis victory · ':m.boss?'Boss victory · ':m.kind==='collect'?'Collected · ':m.kind==='drop'?'Dropped · ':m.kind==='death'?'Fallen · ':m.kind==='kill'?'Defeated · ':'Recorded · ')+m.name+(m.stars?' · '+m.stars+' ★':'')+(m.amount>1&&['collect','drop'].includes(m.kind)?' × '+m.amount:'')+(m.rarity?' · '+m.rarity:'');}
 function excerpt(text){const first=sagaProse(text).split(/\n\s*\n/)[0];return first.length>185?first.slice(0,182)+'\u2026':first;}
 function render(){if(!active)return;const m=points[Math.floor(position)]||points[0];panel.hidden=false;layout.classList.add('with-journey');dock.hidden=!points.length;panel.innerHTML=border+scene(m)+'<button id="closeJourney" class="journey-close" aria-label="Close journey">×</button><div class="journey-story-body"><p class="eyebrow">'+(points.length?'MOMENT <span id="journeyMomentNumber">'+(Math.floor(position)+1)+'</span> OF '+points.length:'A CHAPTER WITHOUT SHARED LOCATIONS')+'</p><h2 id="journeySceneTitle">'+esc(m?.sceneTitle||active.title)+'</h2><p id="journeyPassage" class="journey-excerpt">'+esc(m?.sceneText||excerpt(active.excerpt))+'</p><div class="journey-evidence"><span id="journeyEvidenceIcon">'+glyph(icon(m))+'</span><div><small>RECORDED MOMENT</small><strong id="journeyEvidence">'+esc(record(m))+'</strong><span id="journeyTeam">'+esc(m?(m.team?.map(p=>p.name).join(' & ')||m.playerName)+' · '+date(m.utc):'')+'</span></div></div><a class="journey-read" href="#journey/'+encodeURIComponent(active.id)+'?world='+encodeURIComponent(state.filter.world)+'">Read the full saga <span>→</span></a><small class="journey-provenance">Story passage · fiction inspired by recorded adventures</small><label class="journey-track">Journey perspective<select id="journeyTrack"><option value="">All recorded participants</option>'+[...new Map(allPoints.map(m=>[m.playerId,m.playerName])).entries()].map(([id,name])=>'<option value="'+esc(id)+'">'+esc(name)+'</option>').join('')+'</select></label><ol id="journeyTimeline">'+points.map((m,i)=>'<li><button type="button" data-journey-moment="'+i+'">'+glyph(icon(m))+'<span>'+esc(m.sceneTitle||record(m))+'<small>'+esc(m.playerName)+' · '+esc(date(m.utc))+'</small></span></button></li>').join('')+'</ol>'+(active.truncated?'<p class="muted">Showing up to six highlights from retained moments. Gaps are left unconnected.</p>':'')+'</div>';
 $('closeJourney').onclick=()=>{load.serial++;detailBusy=false;responseKey='';pause();active=null;points=[];panel.hidden=dock.hidden=true;layout.classList.remove('with-journey');if(document.body.dataset.page==='journey')location.hash='world';draw();};
 panel.querySelector('.journey-read').onclick=e=>{if(document.body.dataset.page==='journey'){e.preventDefault();$('journeyChapter').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});}};$('journeyTimeline').onclick=e=>{const b=e.target.closest('[data-journey-moment]');if(b)seek(Number(b.dataset.journeyMoment),true);};
 $('journeyTrack').value=selectedTrack;$('journeyTrack').onchange=()=>{pause();selectedTrack=$('journeyTrack').value;points=selectedTrack?allPoints.filter(m=>m.playerId===selectedTrack):allPoints;position=0;render();fitJourney();draw();};
 if($('journeyTrack').options.length<=2)$('journeyTrack').parentElement.hidden=true;$('journeyScrub').max=Math.max(0,points.length-1);$('journeyPlay').disabled=points.length<2;updateMoment();
 $('journeyTitle').textContent=active.title;$('journeyEyebrow').textContent=(active.scope==='server'?"THE FELLOWSHIP'S SAGA":(state.data.players.find(p=>p.playerId===active.playerId)?.name||'A Viking')+"'S SAGA")+' · '+date(active.utc);
 $('journeyChapter').innerHTML='<p class="eyebrow">THE FULL CHAPTER</p><h2>'+esc(active.title)+'</h2><div class="prose">'+esc(sagaProse(active.text))+'</div><p class="muted">'+esc((active.participants||[]).map(p=>p.name).join(' · '))+'</p><details><summary>Recorded evidence & story source</summary><ul>'+(active.facts||[]).map(f=>'<li>'+esc(f)+'</li>').join('')+'</ul><p>AI narrative · '+esc(active.model)+'. Illustrations are thematic; connections are not tracked footsteps.</p></details>';
 }
 function updateMoment(){const index=Math.min(points.length-1,Math.floor(position)),m=points[index];$('journeyScrub').value=position;$('journeyCount').textContent=points.length?(index+1)+' / '+points.length:'';$('journeyScrub').setAttribute('aria-valuetext',m?(index+1)+' of '+points.length+': '+record(m):'No moments');if(!m)return;$('journeySceneTitle').textContent=m.sceneTitle||active.title;$('journeyPassage').textContent=m.sceneText||excerpt(active.excerpt);$('journeyPassage').classList.toggle('is-scene',!!m.sceneText);$('journeyMomentNumber').textContent=index+1;$('journeyEvidence').textContent=record(m);$('journeyTeam').textContent=(m.team?.map(p=>p.name).join(' & ')||m.playerName)+' · '+date(m.utc);$('journeyEvidenceIcon').innerHTML=glyph(icon(m));for(const b of $('journeyTimeline').querySelectorAll('button')){const selected=Number(b.dataset.journeyMoment)===index;b.setAttribute('aria-current',String(selected));}const a=art(m),img=panel.querySelector('.journey-landscape');if(img&&img.getAttribute('src')!=='/biomes/grounded/'+a.biome+'-1920.webp')img.src='/biomes/grounded/'+a.biome+'-1920.webp';let boss=panel.querySelector('.journey-boss');if(a.boss){if(!boss){boss=document.createElement('img');boss.className='journey-boss';boss.alt='';panel.querySelector('.journey-art').append(boss);}if(boss.getAttribute('src')!==a.boss)boss.src=a.boss;}else boss?.remove();}
 function seek(value,center=false){pause();position=Math.max(0,Math.min(points.length-1,value));updateMoment();if(center){const m=points[Math.floor(position)];if(m){view.x=m.x;view.z=m.z;requestMapDraw();requestMapDetail();}}draw();}
 function fitJourney(){const pts=active?points:rows.map(r=>r.anchor).filter(Boolean);if(!pts.length)return;const xs=pts.map(m=>m.x),zs=pts.map(m=>m.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),w=canvas.clientWidth,h=canvas.clientHeight;view.scale=Math.max(minimumMapScale(),Math.min(2,Math.max(80,w-320)/Math.max(100,maxX-minX),Math.max(80,h-390)/Math.max(100,maxZ-minZ)));view.x=(minX+maxX)/2;view.z=(minZ+maxZ)/2-25/view.scale;state.fit=false;requestMapDraw();requestMapDetail();}
 $('journeyFit').onclick=fitJourney;$('journeyScrub').oninput=()=>seek(Number($('journeyScrub').value));
 function tick(t){if(!playing||document.hidden||!visible()){pause();return;}if(last){const delta=Math.min(80,t-last);position+=delta/3500*Number($('journeySpeed').value);}last=t;if(position>=points.length-1){position=points.length-1;pause();}const old=Number($('journeyMomentNumber')?.textContent)-1;if(Math.floor(position)!==old)updateMoment();else $('journeyScrub').value=position;
  // Camera updates only on arrival, never every animation frame.
  if($('journeyFollow').checked&&Math.floor(position)!==old){const m=points[Math.floor(position)];view.x=m.x;view.z=m.z;requestMapDraw();requestMapDetail();}draw();if(playing)raf=requestAnimationFrame(tick);
 }
 $('journeyPlay').onclick=()=>{if(playing){pause();return;}if(points.length<2)return;if(position>=points.length-1)position=0;playing=true;last=0;$('journeyPlay').textContent='Ⅱ';$('journeyPlay').setAttribute('aria-label','Pause journey');raf=requestAnimationFrame(tick);};
 // Decorative world-space curve: stable while zooming, with exact recorded endpoints.
 function trailPoint(a,b,t){const dx=b.x-a.x,dz=b.z-a.z,length=Math.hypot(dx,dz),amplitude=Math.min(30,length*.13),wave=Math.sin(t*Math.PI*2)*amplitude;return {x:a.x+dx*t+(length?-dz/length*wave:0),z:a.z+dz*t+(length?dx/length*wave:0)};}
 function trailStroke(a,b,end){const steps=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)*1.5/8));let pen=false;paint.beginPath();for(let n=0;n<=Math.ceil(steps*end);n++){const t=Math.min(end,n/steps),p=trailPoint(a,b,t),xy=screen(p.x,p.z);if(exploredPoint(p.x,p.z)){if(pen)paint.lineTo(...xy);else paint.moveTo(...xy);pen=true;}else pen=false;}paint.stroke();}
 function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(surface.width!==Math.round(w*dpr))surface.width=Math.round(w*dpr);if(surface.height!==Math.round(h*dpr))surface.height=Math.round(h*dpr);paint.setTransform(dpr,0,0,dpr,0,0);paint.clearRect(0,0,w,h);hits=[];if(!enabled||!visible()||!w||!h)return;const track=$('journeyTrack')?.value||'';
  const visiblePoints=active?points.map((m,i)=>({m,i})).filter(({m})=>!track||m.playerId===track):rows.filter(r=>r.anchor).map((r,i)=>({m:r.anchor,i,chapter:r.chapter}));
  const projected=visiblePoints.map(p=>({...p,xy:screen(p.m.x,p.m.z)}));
  // Declutter coincident moment icons with short spokes to their true location.
  const occupied=[];for(const p of projected){const [x,y]=p.xy;let display=[x,y];for(let n=0;n<240;n++){const angle=n*2.399963,radius=n?28*Math.sqrt(n):0;display=[x+Math.cos(angle)*radius,y+Math.sin(angle)*radius];if(occupied.every(q=>Math.abs(q[0]-display[0])>=90||Math.abs(q[1]-display[1])>=115))break;}p.display=display;occupied.push(display);}
  if(active){paint.lineWidth=2;paint.setLineDash([2,7]);paint.lineCap='round';for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];if(b.breakBefore||(track&&(a.playerId!==track||b.playerId!==track)))continue;paint.strokeStyle=i<=position?'#f3ce78':'#b893505c';trailStroke(a,b,1);if(i===Math.floor(position)+1&&position%1>0){paint.strokeStyle='#f3ce78';trailStroke(a,b,position%1);}}paint.setLineDash([]);
   const index=Math.floor(position),a=points[index],b=points[index+1],fraction=position-index;
   if(a&&b&&!b.breakBefore&&(!track||a.playerId===track)&&!reduced.matches){const p=trailPoint(a,b,fraction);if(exploredPoint(p.x,p.z)){const before=trailPoint(a,b,Math.max(0,fraction-.001)),after=trailPoint(a,b,Math.min(1,fraction+.001)),[px,py]=screen(p.x,p.z),[x,y]=screen(before.x,before.z),[xx,yy]=screen(after.x,after.z);paint.save();paint.translate(px,py);paint.rotate(Math.atan2(yy-y,xx-x));paint.shadowColor='#ffd880';paint.shadowBlur=14;paint.fillStyle='#fff2b5';paint.beginPath();paint.moveTo(10,0);paint.lineTo(-7,-6);paint.lineTo(-3,0);paint.lineTo(-7,6);paint.closePath();paint.fill();paint.restore();}}
  }
  for(const p of projected){const [x,y]=p.display;if(x<-40||y<-40||x>w+40||y>h+40||!exploredPoint(p.m.x,p.m.z))continue;const selected=active&&p.i===Math.floor(position),major=active&&p.m.kind==='kill'&&(p.m.boss||p.m.nemesisBoss),banner=!!p.chapter||(active&&p.i===0&&!p.m.sceneTitle&&!major),r=banner?9:major?34:selected?25:22;paint.save();if(p.display!==p.xy){paint.strokeStyle='#e3bd7388';paint.beginPath();paint.moveTo(...p.xy);paint.lineTo(x,y);paint.stroke();}paint.translate(x,y);paint.beginPath();paint.roundRect(-r,-r,r*2,r*2,major?11:7);paint.fillStyle='#10242cef';paint.fill();paint.strokeStyle=selected?'#ffe3a0':'#d5ad64';paint.lineWidth=selected?2.5:1.4;if(selected){paint.shadowColor='#edbb50';paint.shadowBlur=15;}paint.stroke();paint.shadowBlur=0;if(major){paint.beginPath();paint.roundRect(-r+5,-r+5,r*2-10,r*2-10,7);paint.strokeStyle='#f3ce78';paint.lineWidth=.8;paint.stroke();}paint.save();if(banner){paint.strokeStyle='#d5ad64';paint.beginPath();paint.moveTo(0,-r);paint.lineTo(0,-66);paint.stroke();paint.fillStyle='#deb463';paint.beginPath();paint.moveTo(1,-65);paint.lineTo(29,-65);paint.lineTo(26,-28);paint.lineTo(13,-34);paint.lineTo(1,-28);paint.closePath();paint.fill();paint.translate(4,-61);paint.scale(20/24,20/24);}else{const size=major?32:20;paint.translate(-size/2,-size/2);paint.scale(size/24,size/24);}paint.strokeStyle=banner?'#14242b':'#f2e6cc';paint.lineWidth=1.6;paint.lineCap='round';paint.lineJoin='round';paint.stroke(new Path2D(paths[banner?'quill':icon(p.m)]));paint.restore();paint.font='12px system-ui';paint.textAlign='center';paint.fillStyle='#fff0d1';if(active)paint.fillText(String(p.i+1),0,r+16);paint.restore();hits.push({x,y:banner?y-28:y,r:banner?40:r+5,...p});}
 }
 function hit(x,y){if(!enabled)return false;const h=[...hits].reverse().find(p=>Math.hypot(p.x-x,p.y-y)<p.r);if(!h)return false;if(h.chapter)load(h.chapter.id,true);else seek(h.i);return true;}
 function chooseRouteWorld(){const requested=new URLSearchParams(location.hash.split('?')[1]||'').get('world');if(!requested||requested===state.filter.world)return true;if(!state.data)return false;if(![...$('world').options].some(o=>o.value===requested)){$('journeyChapter').textContent='This chapter belongs to a world that is not available on this host.';return false;}$('world').value=requested;$('world').onchange();return false;}
 $('world').addEventListener('change',()=>{if(document.body.dataset.page==='journey')location.hash='world';});
 function route(){const dedicated=document.body.dataset.page==='journey';if(dedicated){$('journeyAtlas').append(atlas);atlas.classList.add('journey-dedicated');enabled=true;$('journeyLayer').checked=true;let id='';try{id=decodeURIComponent((location.hash.split('/')[1]||'').split('?')[0]);}catch{}if(!chooseRouteWorld())return;if(id&&state.filter.world)load(id,active?.id!==id);refresh();}else{home.after(atlas);atlas.classList.remove('journey-dedicated');if(!visible())pause();}requestAnimationFrame(()=>{requestMapDraw();draw();});}
 new ResizeObserver(draw).observe(frame);new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)pause();}).observe(frame);document.addEventListener('visibilitychange',()=>{if(document.hidden){pausedByVisibility=playing;pause();}else if(pausedByVisibility){pausedByVisibility=false;/* Explicit resume avoids surprising movement. */}});
 window.SagaJourney={draw,hit,route,refresh,reset,manualPan(){if($('journeyFollow'))$('journeyFollow').checked=false;},debug:()=>({enabled,playing,position,points:points.length,chapters:rows.length,active:active?.id,hits:hits.length,markers:hits.map(p=>({x:p.x,y:p.y,index:p.i,radius:p.r,boss:!!(p.m.boss||p.m.nemesisBoss)})),moments:points.map(p=>({x:p.x,z:p.z}))})};route();
})();
